const T1 = "Theme 1: Matter – Structures & Properties";

const svgStates = `<svg viewBox="0 0 360 140" xmlns="http://www.w3.org/2000/svg"><rect width="360" height="140" fill="#1c222d"/><text x="50" y="22" fill="#5eead4" font-size="11" font-family="system-ui">SOLID</text><g fill="#a78bfa"><circle cx="40" cy="55" r="5"/><circle cx="58" cy="50" r="5"/><circle cx="52" cy="70" r="5"/><circle cx="70" cy="62" r="5"/></g><text x="190" y="22" fill="#5eead4" font-size="11">LIQUID</text><g fill="#5eead4"><circle cx="205" cy="55" r="4"/><circle cx="220" cy="50" r="4"/><circle cx="215" cy="68" r="4"/><circle cx="232" cy="60" r="4"/><circle cx="245" cy="52" r="4"/></g><text x="295" y="22" fill="#5eead4" font-size="11">GAS</text><g fill="#fb923c"><circle cx="300" cy="52" r="3"/><circle cx="318" cy="48" r="3"/><circle cx="310" cy="68" r="3"/><circle cx="328" cy="62" r="3"/></g><text x="15" y="128" fill="#8b95a8" font-size="9">Fixed lattice · vibrate</text><text x="175" y="128" fill="#8b95a8" font-size="9">Random positions · close</text><text x="285" y="128" fill="#8b95a8" font-size="9">Far apart · rapid motion</text></svg>`;

const svgAtom = `<svg viewBox="0 0 260 150" xmlns="http://www.w3.org/2000/svg"><rect width="260" height="150" fill="#1c222d"/><circle cx="130" cy="75" r="45" fill="none" stroke="#6366f1" stroke-width="2" stroke-dasharray="5 4"/><circle cx="130" cy="75" r="14" fill="#f87171"/><text x="118" y="80" fill="#fff" font-size="10">nucleus</text><circle cx="90" cy="50" r="4" fill="#5eead4"/><circle cx="175" cy="95" r="4" fill="#5eead4"/><circle cx="165" cy="48" r="4" fill="#5eead4"/><text x="12" y="138" fill="#8b95a8" font-size="9">Protons+neutrons in nucleus · electrons in shells</text></svg>`;

const svgBond = `<svg viewBox="0 0 280 110" xmlns="http://www.w3.org/2000/svg"><rect width="280" height="110" fill="#1c222d"/><text x="8" y="18" fill="#5eead4" font-size="10">IONIC</text><text x="10" y="48" fill="#a78bfa" font-size="22">Na⁺</text><text x="120" y="48" fill="#fb923c" font-size="22">Cl⁻</text><line x1="55" y1="42" x2="105" y2="42" stroke="#666" stroke-width="2"/><text x="8" y="88" fill="#5eead4" font-size="10">COVALENT</text><circle cx="200" cy="82" r="12" fill="none" stroke="#4ade80" stroke-width="2"/><circle cx="235" cy="82" r="12" fill="none" stroke="#4ade80" stroke-width="2"/><line x1="212" y1="82" x2="223" y2="82" stroke="#4ade80" stroke-width="3"/></svg>`;

function Q(q, a, b, c, d, i, e) {
  return [q, [a, b, c, d], i, e];
}

function TF(s, ok, x) {
  return [s, ok, x];
}

export const topicsTheme1 = [
  {
    id: "1",
    theme: T1,
    title: "Experimental Design",
    cheatBlocks: [
      { title: "Variables", points: ["**Independent** — what you change (one factor).", "**Dependent** — what you measure.", "**Control variables** — kept constant for a fair test.", "Only **one** independent variable should change per experiment."] },
      { title: "Validity & reliability", points: ["**Reliability** — repeat and get similar results (reduce random error).", "**Accuracy** — close to true value; **precision** — repeatable readings.", "**Systematic error** — same direction every time (e.g. zero error).", "**Random error** — scatter; reduce by repeats and averaging."] },
      { title: "Graphs", points: ["Plot **dependent** on **y-axis**, **independent** on **x-axis**.", "Line of best fit for proportional relationships; identify anomalies.", "Units on axes; sensible scale."] },
      { title: "Risk & method", points: ["List hazards (corrosive, flammable, hot).", "Control measures: goggles, fume cupboard, low concentration.", "Step-by-step method so others can repeat."] },
    ],
    flashcards: [
      { front: "Independent variable?", back: "The one you deliberately change." },
      { front: "Why control variables?", back: "So only the tested factor affects the result." },
      { front: "Random vs systematic error?", back: "Random: scatter. Systematic: consistent bias." },
      { front: "Hypothesis vs prediction?", back: "Hypothesis is testable; prediction is expected outcome." },
      { front: "Why pilot experiment?", back: "Check method, range, safety before full run." },
      { front: "Anomalous result?", back: "Outlier — often excluded if clear mistake." },
      { front: "Repeat vs replicate?", back: "Repeat: same person; replicate: different runs/people." },
      { front: "Blind testing?", back: "Reduces bias when subject doesn't know which is which." },
      { front: "Resolution of instrument?", back: "Smallest change it can detect." },
      { front: "Uncertainty?", back: "Half smallest division or stated instrument error." },
      { front: "Correlation vs causation?", back: "Correlation doesn't prove one caused the other." },
      { front: "Control group?", back: "Baseline without the treatment for comparison." },
      { front: "Sample size?", back: "Larger sample usually more representative." },
      { front: "Fair test checklist?", back: "One IV, measure DV, list and fix controls." },
    ],
    quiz: [
      Q("Fair test requires changing:", "Only one independent variable", "All variables", "Only the dependent", "Nothing", 0, "One factor at a time."),
      Q("Dependent variable is:", "What you measure", "What you keep fixed", "The hypothesis", "Apparatus list", 0, "Response to your change."),
      Q("Reliability improves when you:", "Change two variables", "Repeat measurements", "Use one reading only", "Skip units", 1, "Repeats show consistency."),
      Q("Systematic error:", "Averages to zero", "Shifts all results similarly", "Only in gases", "Impossible", 1, "Same bias each time."),
      Q("Random error:", "Always +5%", "Causes scatter", "Only human", "Removes need for graph", 1, "Unpredictable variation."),
      Q("On a graph, independent variable usually goes on:", "y-axis", "x-axis", "Neither", "Title only", 1, "Convention: x = what you change."),
      Q("An anomaly should be:", "Always kept", "Investigated; may exclude if error proven", "Doubled", "Ignored silently", 1, "Document decision."),
      Q("Precision means:", "Close to literature value", "Readings cluster tightly", "Fast experiment", "Cheap", 1, "Repeatability."),
      Q("Accuracy means:", "Many repeats", "Close to true value", "Large sample", "Short report", 1, "Correctness."),
      Q("Control experiment helps:", "Waste time", "Isolate effect of the variable tested", "Remove all errors", "Avoid graph", 1, "Comparison baseline."),
      Q("Zero error on a meter:", "Random", "Systematic", "Never happens", "Only digital", 1, "Consistent offset."),
      Q("Sample should be:", "Always size 1", "Representative of population", "Only extremes", "Random words", 1, "Generalisable."),
      Q("Risk assessment includes:", "Only results", "Hazard + control measure", "Only cost", "Exam date", 1, "Safety first."),
      Q("Valid conclusion requires:", "Fair test + relevant data", "Many colours on graph", "Short method", "No repeats", 0, "Logic + evidence."),
      Q("Operational definition:", "Defines how you measure a variable", "Defines exam board", "Unit only", "Hypothesis", 0, "Measurable definition."),
      Q("Blind trial reduces:", "Cost only", "Observer bias", "Time", "Apparatus need", 1, "Expectation effects."),
      Q("Line of best fit:", "Joins every dot", "Shows trend; balances scatter", "Horizontal only", "Optional for marks", 1, "Trend line."),
      Q("Interpolation vs extrapolation:", "Same", "Interpolation within data; extrapolation beyond — riskier", "Only extrapolation safe", "Neither used", 1, "Outside range uncertain."),
      Q("Resolution 0.1 cm means:", "Error 10%", "Smallest reading step 0.1 cm", "Length 0.1 cm", "Volume", 1, "Instrument precision."),
      Q("Peer review improves:", "Font size", "Credibility of method", "Speed only", "Nothing", 1, "Others check design."),
      Q("Controlled variable example when testing temp on rate:", "Temperature", "Concentration of acid", "Time measured", "Product colour", 1, "Keep concentration same."),
      Q("Pilot study:", "Final exam", "Small trial to refine method", "Only theory", "Graph type", 1, "Practice run."),
      Q("Recording raw data means:", "Only averages", "Original readings before manipulation", "Final conclusion", "Teacher marks", 1, "Primary data."),
      Q("Ethical sampling (humans):", "Force participation", "Informed consent", "Hide purpose always", "No documentation", 1, "Consent matters."),
      Q("Uncertainty bar on graph shows:", "Artist choice", "Range of doubt in measurement", "Exam board", "Colour code", 1, "Error representation."),
      Q("If gradient units are mol/dm³ ÷ s, you have:", "Rate of reaction", "Density", "Pressure", "Voltage", 0, "Concentration change per time."),
    ],
    trueFalse: [
      TF("More repeats always remove systematic error.", false, "Repeats reduce random error; systematic needs calibration/fix."),
      TF("You can change two independent variables and still claim which caused the effect.", false, "Confounded variables — unclear cause."),
      TF("The dependent variable should be plotted on the y-axis in chemistry kinetics graphs.", true, "y = measured response."),
      TF("A very precise data set can still be inaccurate.", true, "Clustered but offset from true value."),
      TF("Control variables are irrelevant if you do the experiment quickly.", false, "They still affect validity."),
      TF("Extrapolating far beyond data range is usually reliable.", false, "Assumptions may break."),
      TF("Random errors often follow a normal distribution around the mean.", true, "Central limit idea."),
      TF("Recording only 'nice' results without outliers is good practice.", false, "Cherry-picking is dishonest."),
      TF("A hypothesis must be falsifiable.", true, "Science tests refutation."),
      TF("Same student repeating 10 times is weaker than independent replication.", true, "Same bias may persist."),
      TF("Digital readout always means higher accuracy than analogue.", false, "Resolution and calibration matter."),
      TF("Risk: concentrated acid — wear eye protection.", true, "Standard lab rule."),
    ],
    orderGame: ["State aim and hypothesis", "List hazards and controls", "List apparatus", "Describe method step-by-step", "Tabulate raw results", "Process data and graph", "Evaluate and conclude"],
    orderTitle: "Typical investigation write-up",
  },
  {
    id: "2",
    theme: T1,
    title: "Methods of Purification and Analysis",
    cheatBlocks: [
      { title: "Separation", points: ["**Filtration** — residue + filtrate.", "**Crystallisation** — saturate, cool slowly, filter crystals.", "**Distillation** — volatile vs non-volatile; **fractional** for close boiling points.", "**Chromatography** — partition between mobile and stationary phase."] },
      { title: "Rf", points: ["Rf = distance spot ÷ distance solvent front (both from baseline).", "0 ≤ Rf ≤ 1; same conditions → same Rf for same substance.", "Pencil baseline; don't use ink."] },
      { title: "Solubility rules (context)", points: ["Many nitrates soluble; group 1 salts often soluble.", "AgCl, BaSO₄, CaCO₃ common insoluble examples in tests."] },
    ],
    flashcards: [
      { front: "Rf formula?", back: "spot distance / solvent front distance." },
      { front: "Fractional distillation use?", back: "Separate miscible liquids with close bp." },
      { front: "Why pencil on chromatography paper?", back: "Ink would run and smear." },
      { front: "Filtrate?", back: "Liquid passing through filter paper." },
      { front: "Residue?", back: "Solid left on filter paper." },
      { front: "Slow evaporation for crystals?", back: "Larger, purer crystals form." },
      { front: "Stationary phase in paper chromatography?", back: "Water adsorbed on paper fibres." },
      { front: "Mobile phase?", back: "Solvent moving up the paper." },
      { front: "Simple distillation best for?", back: "Separating volatile liquid from dissolved solid." },
      { front: "Immiscible liquids?", back: "Separate in funnel; tap off layers." },
      { front: "Sublimation example?", back: "Iodine or dry ice — solid to vapour." },
      { front: "Decantation?", back: "Pour off liquid leaving sediment." },
      { front: "Centrifugation?", back: "Denser particles pack at bottom." },
      { front: "Why anti-bumping granules?", back: "Even boiling in distillation." },
    ],
    quiz: [
      Q("Rf is calculated as:", "Front ÷ spot", "Spot ÷ front", "Mass ÷ volume", "Time ÷ distance", 1, "Spot over solvent front."),
      Q("Two liquids bp 82°C and 78°C best separated by:", "Simple distillation only", "Fractional distillation", "Filtration", "Magnet", 1, "Close bp need fractionating column."),
      Q("Pure salt from rock salt + water:", "Filter only", "Dissolve, filter sand, evaporate", "Distil water only", "Burn", 1, "NaCl soluble; insoluble grit filtered."),
      Q("Chromatography separates by:", "Boiling point only", "Different affinity for phases", "Colour only", "Density of beaker", 1, "Partition."),
      Q("Baseline in pencil because:", "Pencil cheaper", "Ink dissolves and interferes", "Exam rule", "Pencil darker", 1, "Soluble ink runs."),
      Q("Higher Rf means:", "Less soluble in mobile phase", "More time in mobile phase / travels further", "Heavier atom", "Always ionic", 1, "Moves farther with solvent."),
      Q("BaCl₂ test for sulfate gives:", "Gas", "White BaSO₄ ppt", "Blue solution", "Silver mirror", 1, "Insoluble sulfate."),
      Q("Distillation flask should not be:", "Round bottom", "Filled completely", "Heated with condenser", "Clamped", 1, "Needs head space — bumping."),
      Q("Cooling condenser water flow:", "Bottom in top out", "Top in bottom out", "No water", "Either", 0, "Counter-current cooling efficient."),
      Q("Crystallisation from hot saturated solution on cooling:", "Gas forms", "Crystals form as solubility drops", "Liquid boils", "Paper chars", 1, "Less soluble when cold."),
      Q("Which is NOT a purification method:", "Filtration", "Photosynthesis", "Distillation", "Chromatography", 1, "Photosynthesis is synthesis."),
      Q("Solvent front must:", "Stay below spotted baseline", "Never move", "Be above baseline", "Touch top first", 2, "Solvent rises from baseline."),
      Q("Mixed ink spots → several spots after run means:", "Single pure compound", "Several components", "Error only", "Paper wet", 1, "Separated dyes."),
      Q("Volatile from non-volatile:", "Chromatography only", "Simple distillation", "Only filtration", "Only titration", 1, "Vapour condenses."),
      Q("Immiscible oil + water:", "One phase", "Separate layers", "Always dissolve", "Same density", 1, "Use separating funnel."),
      Q("Anti-bumping granules:", "Increase bp", "Smooth boiling", "Absorb product", "Colour indicator", 1, "Nucleation sites."),
      Q("If Rf = 0.4 and front 10 cm, spot distance:", "25 cm", "4 cm", "2.5 cm", "0.04 cm", 1, "0.4×10=4 cm."),
      Q("Ethanol + water (wide bp gap) could use:", "Either simple or fractional", "Only chromatography", "Only electrolysis", "Decantation", 0, "Simple may suffice; fractional finer."),
      Q("Dry product after filtration:", "Leave wet", "Desiccator or oven low T", "Burn", "Add water", 1, "Remove surface water."),
      Q("Paper chromatography is:", "Always ascending", "Only gas phase", "Partition between stationary water and solvent", "Electrophoresis", 2, "Classic explanation."),
      Q("Which pair is separated by sublimation in lab context:", "NaCl + sand", "Iodine + sand", "Oil + water", "Cu + Fe", 1, "Iodine sublimes."),
      Q("Tailing spot in chromatography may mean:", "Too concentrated spot", "Perfect technique", "No solvent", "Rf = 1 always", 0, "Overload smears."),
      Q("Recrystallisation purifies by:", "Different solubility of impurities", "Burning impurities", "Magnet", "Sound", 0, "Impurity stays in solution or filters out."),
      Q("Gas chromatography mobile phase is:", "Paper", "Inert gas", "Only water", "Mercury", 1, "Carrier gas."),
      Q("Thin layer chromatography stationary phase:", "Glass rod", "Silica on plate", "Only filter paper", "Ice", 1, "TLC plate."),
      Q("Azeotrope (e.g. some ethanol-water) means:", "Easy 100% separation by one distillation", "Constant boiling mixture — limit of simple separation", "No liquid", "Only solid", 1, "Fractional still may be needed."),
    ],
    trueFalse: [
      TF("Rf can be greater than 1.", false, "By definition ratio ≤ 1."),
      TF("Same compound always has same Rf if solvent and temperature unchanged.", true, "Characteristic under fixed conditions."),
      TF("You should spot with a thick blob for best results.", false, "Small concentrated spot — less tailing."),
      TF("Distillation separates miscible liquids by density.", false, "By volatility / boiling point."),
      TF("Filtration separates an insoluble solid from a liquid.", true, "Classic use."),
      TF("All nitrates are insoluble.", false, "Most nitrates are soluble."),
      TF("Water in condenser jacket should flow opposite to vapour direction.", true, "Efficient cooling."),
      TF("Chromatography paper should touch the very bottom of the solvent in the tank.", false, "Baseline above liquid level."),
      TF("Fractionating column has more surface for repeated evaporation-condensation.", true, "Theoretical plates."),
      TF("Centrifugation speeds up settling of fine precipitates.", true, "Artificial 'gravity'."),
      TF("Simple distillation gives pure azeotropic ethanol-water in one step easily.", false, "Often ~96% ethanol azeotrope."),
      TF("Sublimation is solid to gas without liquid.", true, "Definition."),
    ],
    orderGame: ["Draw pencil baseline", "Spot sample", "Add solvent below baseline", "Seal tank", "Run until near top", "Dry and locate spots"],
    orderTitle: "Paper chromatography",
  },
  {
    id: "3",
    theme: T1,
    title: "Kinetic Particle Theory",
    cheatBlocks: [
      { title: "States", points: ["**Solid** — ordered lattice; vibrate; definite shape/volume.", "**Liquid** — disordered close packing; flow; definite volume.", "**Gas** — random motion; negligible IM forces; fill container."] },
      { title: "Energy", points: ["Heating increases **average** kinetic energy.", "Melting, boiling, evaporation absorb energy.", "Condensation, freezing release energy."] },
      { title: "Gas laws (qualitative)", points: ["Higher T at constant V → higher **pressure** (more violent collisions).", "**Diffusion** — gases mix; rate ∝ speed of particles; lighter molecules often faster."] },
    ],
    infographics: [{ svg: svgStates, caption: "Particle arrangement: solid, liquid, gas" }],
    flashcards: [
      { front: "Why can liquids flow?", back: "Particles slide past one another." },
      { front: "Gas pressure cause?", back: "Particles colliding with walls." },
      { front: "Evaporation vs boiling?", back: "Evaporation surface any T; boiling throughout at bp." },
      { front: "Sublimation?", back: "Solid → gas without liquid." },
      { front: "Brownian motion?", back: "Random jostling of suspended particles by fluid molecules." },
      { front: "Why gas is compressible?", back: "Large empty space between particles." },
      { front: "Heating a gas in fixed volume?", back: "Pressure increases." },
      { front: "Diffusion in liquids slower than gases?", back: "Yes — slower particle motion." },
      { front: "Melting point?", back: "Solid and liquid coexist at equilibrium." },
      { front: "Condensation releases energy?", back: "Yes — particles lose KE." },
      { front: "Ideal gas assumptions?", back: "No forces; point particles; elastic collisions (model)." },
      { front: "Why smell spreads?", back: "Diffusion of volatile molecules in air." },
      { front: "Expansion on heating (most solids)?", back: "Particles vibrate more — average separation increases." },
      { front: "Triple point?", back: "T,P where solid, liquid, gas coexist (advanced)." },
    ],
    quiz: [
      Q("Gas particles are best described as:", "Fixed in rows", "Far apart with random motion", "Only vibrating in place", "Not moving at 0 K only", 1, "Kinetic model."),
      Q("Liquids have definite:", "Shape and volume", "Volume only", "Neither", "Shape only", 1, "Take container shape."),
      Q("Boiling is:", "Only at surface", "Throughout liquid at bp", "Only for metals", "Endothermic for surroundings", 1, "Bubbles form inside."),
      Q("Evaporation cools liquid because:", "Fast molecules escape", "Slow molecules escape", "No energy change", "Air heats it", 0, "Removes high-KE molecules."),
      Q("Diffusion fastest in:", "Solid", "Liquid", "Gas", "Same all", 2, "Higher speed, larger gaps."),
      Q("Compressing gas at constant T:", "Increases pressure", "Decreases collisions", "Removes molecules", "Becomes solid always", 0, "More collisions per area."),
      Q("Heating sealed rigid gas:", "Pressure drops", "Pressure rises", "Volume rises", "Mass leaves", 1, "Harder hits on walls."),
      Q("Melting is:", "Exothermic", "Endothermic", "No energy", "Only for ice", 1, "Breaks some lattice bonds."),
      Q("Deposition is:", "Gas to solid", "Solid to gas", "Liquid to gas", "Gas to liquid", 0, "Reverse sublimation."),
      Q("Which state has strongest typical IM forces?", "Gas", "Liquid", "Solid", "Same", 2, "Lattice binding."),
      Q("Brownian motion evidence for:", "Electrons only", "Moving atoms/molecules", "Gravity", "Light waves", 1, "Particle kinetic evidence."),
      Q("Perfume across room is mainly:", "Convection only", "Diffusion", "Condensation", "Ionisation", 1, "Random molecular motion."),
      Q("At same T, H₂ vs O₂ average speed:", "O₂ faster", "H₂ faster", "Same always", "Zero", 1, "Lighter molecules faster (same KE)."),
      Q("Internal energy of ideal gas increases when:", "Volume doubled at constant T", "Temperature rises", "Pressure drops isothermally", "Mass halved", 1, "KE linked to T."),
      Q("Surface evaporation rate increases with:", "Lower T", "Wind and higher T", "Lower surface area", "Humid air always", 1, "More molecules escape."),
      Q("Solid expands on heating mostly because:", "Atoms destroyed", "Vibration amplitude and spacing increase", "Electrons lost", "Mass increases", 1, "Typical thermal expansion."),
      Q("Gas in syringe sealed — push piston in:", "Pressure decreases", "Pressure increases", "T always drops to zero", "No change", 1, "Boyle's law idea."),
      Q("Liquid boiling point at mountain:", "Higher than sea level", "Lower than sea level", "Same always", "Undefined", 1, "Lower external pressure."),
      Q("Condensation on cold glass:", "Water vapour → liquid", "Liquid → solid", "Solid → gas", "Endothermic for glass", 0, "Gas loses KE."),
      Q("Which is NOT assumed in simple particle model of ideal gas:", "Elastic collisions", "Negligible volume of particles", "Strong attractions at all distances", "Random motion", 2, "Ideal: no IM forces."),
      Q("Diffusion in gel slower than in water because:", "Particles bigger obstacle path", "No difference", "Gravity stronger", "Temperature zero", 0, "Medium hinders motion."),
      Q("Sublimation of dry ice:", "CO₂ solid → gas", "H₂O only", "Metal vapour", "Liquid CO₂ only", 0, "Dry ice sublimes."),
      Q("Rate of diffusion Graham's law (same T):", "Heavier gas faster", "Lighter gas faster", "Independent of mass", "Only liquids", 1, "u ∝ 1/√M."),
      Q("When liquid boils, temperature:", "Rises continuously", "Stays constant until done", "Drops", "Zero", 1, "Latent heat goes to vapour."),
      Q("Gas pressure in container is due to:", "Weight of gas only", "Momentum change at walls", "Colour", "Volume only", 1, "Collisions."),
      Q("Solid to liquid at constant pressure absorbs:", "Latent heat of fusion", "Latent heat of vapourisation", "No heat", "Only light", 0, "Melting."),
    ],
    trueFalse: [
      TF("All particles in a gas have exactly the same speed at a given temperature.", false, "Maxwell-Boltzmann distribution — range of speeds."),
      TF("A liquid has a fixed volume but takes the shape of its container.", true, "Definition."),
      TF("Compressing a liquid is as easy as compressing a gas.", false, "Liquids nearly incompressible."),
      TF("Diffusion proves particles are in continuous random motion.", true, "Classic inference."),
      TF("Boiling point is when vapour pressure equals atmospheric pressure.", true, "Bubble formation stable."),
      TF("Heating always increases volume for every substance in every state.", false, "Water 0–4°C anomaly; some contracts."),
      TF("Gas fills any container because particles move randomly and are far apart.", true, "Kinetic picture."),
      TF("Evaporation only happens at 100°C for water.", false, "Any temperature — surface phenomenon."),
      TF("Sublimation skips the liquid phase.", true, "Solid directly to gas."),
      TF("In a solid, particles have zero kinetic energy at room temperature.", false, "They vibrate — zero point motion."),
      TF("Lighter gas molecules effuse faster through a small hole.", true, "Graham."),
      TF("Condensation is exothermic for the substance condensing.", true, "Energy released to surroundings."),
    ],
  },
  {
    id: "4",
    theme: T1,
    title: "Atomic Structure",
    cheatBlocks: [
      { title: "Particles", points: ["**Proton** +1, mass 1 u; **neutron** 0, ~1 u; **electron** −1, negligible mass.", "In atom: **protons = electrons** (neutral).", "**Atomic number Z** = protons = electrons in neutral atom."] },
      { title: "Mass & ions", points: ["**Mass number A** = protons + neutrons.", "**Isotopes** — same Z, different neutron number.", "**Ion** — electron gain/loss; cation +, anion −."] },
      { title: "Electronic structure", points: ["Shells fill 2,8,8… (O-level pattern).", "**Valence electrons** — outer shell; drive bonding.", "Group number (main) ≈ valence e⁻ for groups 1–2, 7–0 pattern context."] },
    ],
    infographics: [{ svg: svgAtom, caption: "Nucleus + electron shells (schematic)" }],
    flashcards: [
      { front: "Atomic number?", back: "Number of protons." },
      { front: "Mass number?", back: "Protons + neutrons." },
      { front: "Isotope of carbon?", back: "Same 6 protons; C-12 vs C-14 differ in neutrons." },
      { front: "Mg²⁺ formed how?", back: "Mg loses 2 electrons." },
      { front: "Cl⁻?", back: "Cl gains one electron." },
      { front: "Where is mass concentrated?", back: "Nucleus." },
      { front: "Relative atomic mass?", back: "Weighted mean of isotope masses." },
      { front: "First shell max electrons?", back: "2." },
      { front: "Sodium electron arrangement?", back: "2,8,1." },
      { front: "Noble gas outer shell (except He)?", back: "8 electrons (octet)." },
      { front: "α particle composition?", back: "2p + 2n (He nucleus)." },
      { front: "β⁻ emission?", back: "Neutron → proton + electron (atomic number up by 1)."},
      { front: "Ionisation energy trend across period?", back: "Generally increases." },
      { front: "Why smaller atomic radius across period?", back: "Same shell, more nuclear charge pulls electrons in." },
    ],
    quiz: [
      Q("Neutron has charge:", "+1", "-1", "0", "+2", 2, "Neutral."),
      Q("An atom with 15 p and 15 e is:", "Anion", "Cation", "Neutral", "Ion always", 2, "Balanced charges."),
      Q("Ion with 11 p and 10 e:", "Na⁺", "Na⁻", "Ne", "Mg²⁺", 0, "Lost one electron."),
      Q("Isotopes differ in:", "Proton count", "Electron count in neutral", "Neutron count", "Position in table", 2, "Same element."),
      Q("Mass number 23, atomic number 11 → neutrons:", "11", "12", "23", "34", 1, "23−11=12."),
      Q("Which defines the element:", "Neutron number", "Proton number", "Mass number", "Electron shells", 1, "Z unique."),
      Q("Cl atom becomes Cl⁻ by:", "Losing electron", "Gaining electron", "Losing proton", "Fusion", 1, "Needs −1 charge."),
      Q("Relative atomic mass of chlorine ~35.5 because:", "Single isotope", "Mixture of isotopes", "Error", "Only Cl⁻", 1, "35Cl and 37Cl."),
      Q("Electronic config of Al (13):", "2,8,4", "2,8,3", "2,11", "8,5", 1, "2+8+3=13."),
      Q("Valence electrons in group 17 atom:", "1", "7", "8", "2", 1, "Halogens need 1 for octet."),
      Q("Nuclear charge experienced by outer electron across period:", "Decreases", "Increases", "Constant", "Zero", 1, "More protons."),
      Q("Cation is always:", "Larger than parent atom", "Smaller than parent atom", "Same size", "No charge", 1, "Fewer electrons, same nucleus pull."),
      Q("Anion compared to atom:", "Smaller", "Larger", "Same", "No electrons", 1, "More e⁻–e⁻ repulsion."),
      Q("α decay: mass number changes by:", "0", "4 decrease", "4 increase", "1 increase", 1, "He nucleus lost."),
      Q("β⁻ decay Z:", "Decreases by 1", "Increases by 1", "Unchanged", "Doubles", 1, "n→p+e⁻."),
      Q("Which is deflected in electric field:", "Neutron beam", "Electron beam", "γ ray", "All equally", 1, "Charged particles."),
      Q("Isotopes have same:", "Chemical properties mostly", "Mass number always", "Neutron count", "Density in all forms", 0, "Same electron config."),
      Q("Mass spectrometer separates:", "By colour", "By mass/charge", "By taste", "By volume only", 1, "m/z."),
      Q("Half-life is:", "Time for half nuclei decay", "Time to zero", "Double mass", "Bond length", 0, "Radioactivity."),
      Q("γ emission:", "Changes Z", "No change in Z or A", "Adds proton", "Only for metals", 1, "Electromagnetic."),
      Q("First ionisation energy of Na vs Mg:", "Na higher", "Mg higher", "Equal", "Zero", 1, "Mg smaller radius, higher IE."),
      Q("Noble gas unreactive largely because:", "Large atoms", "Full outer shell", "No mass", "Liquid", 1, "Stable config."),
      Q("Number of neutrons in ¹⁴C:", "6", "8", "14", "20", 1, "14−6=8."),
      Q("Species isoelectronic with Ne:", "Na⁺", "F⁻", "Both", "Neither", 2, "10 electrons each."),
      Q("Dalton's atomic theory limitation:", "Atoms indivisible", "Isotopes exist", "Law of multiple proportions", "Conservation of mass", 1, "Substructure discovered."),
      Q("Penetration: s vs p electron near nucleus:", "s less likely", "s more likely", "Same", "Neither exists", 1, "s closer on average."),
      Q("Atomic radius trend down group:", "Decreases", "Increases", "Constant", "Oscillates randomly", 1, "Extra shell."),
    ],
    trueFalse: [
      TF("All atoms of an element must have the same mass number.", false, "Isotopes."),
      TF("A positive ion has fewer electrons than protons.", true, "Cation."),
      TF("The mass of an electron is roughly the same as a proton.", false, "Electron ~1/1836 u."),
      TF("Isotopes show identical chemical reactivity in most reactions.", true, "Same electron arrangement."),
      TF("β⁺ decay decreases atomic number by 1.", false, "β⁺ (positron) decreases Z by 1 — actually proton→neutron; user O-level often β⁻ only."),
      TF("Gamma rays are high-energy electromagnetic waves.", true, "No rest mass."),
      TF("The nucleus contains protons and neutrons in ordinary atoms.", true, "Except H-1 no neutron."),
      TF("Ionisation energy is energy to remove outermost electron from gaseous atom.", true, "Definition."),
      TF("Electrons in the same shell have exactly the same energy in multi-electron atoms.", false, "s,p,d subshell splitting."),
      TF("Atomic number 6 always means carbon.", true, "Identity of element."),
      TF("An atom can gain two protons in a chemical reaction.", false, "Nuclear change, not chemical."),
      TF("Relative atomic mass is dimensionless on the carbon-12 scale.", true, "Ar has no unit."),
    ],
  },
  {
    id: "5",
    theme: T1,
    title: "Chemical Bonding and Structure",
    cheatBlocks: [
      { title: "Ionic", points: ["Metal + non-metal → **electron transfer** → ions.", "**Giant ionic lattice** — high mp, brittle, insulators solid; conduct molten/aqueous."] },
      { title: "Covalent", points: ["Share pairs; **simple molecular** (low mp, often insoluble in water) vs **giant covalent** (diamond, graphite, SiO₂).", "**Intermolecular forces** weak between molecules in simple covalent."] },
      { title: "Metallic", points: ["**Sea of delocalised electrons** + fixed cations.", "Conduct heat/electricity, malleable."] },
    ],
    infographics: [{ svg: svgBond, caption: "Ionic vs covalent (simplified)" }],
    flashcards: [
      { front: "Why molten NaCl conducts?", back: "Ions mobile." },
      { front: "Diamond hardness?", back: "Each C tetrahedral; giant covalent." },
      { front: "Graphite conducts along layers?", back: "Delocalised π electrons between planes." },
      { front: "Metallic bond?", back: "Cations in electron sea." },
      { front: "CO₂ bp low?", back: "Simple molecular; weak IM forces." },
      { front: "SiO₂ mp very high?", back: "Giant covalent network." },
      { front: "Dative covalent bond?", back: "Both electrons from one atom (e.g. NH₄⁺)." },
      { front: "Polar covalent bond?", back: "Unequal sharing — ΔEN." },
      { front: "Hydrogen bonding?", back: "Strong IM force; F,O,N with H." },
      { front: "Ionic crystal brittle?", back: "Ion layers slip → same charges align → repel." },
      { front: "Alloys harder than pure metal?", back: "Different size atoms disrupt layers." },
      { front: "Fullerene?", back: "Molecular carbon cages (e.g. C₆₀)." },
      { front: "Graphene?", back: "Single layer graphite; strong 2D." },
      { front: "Van der Waals?", back: "Weak forces all molecules; stronger for larger surface." },
    ],
    quiz: [
      Q("Which conducts when solid:", "NaCl crystal", "Diamond", "Copper", "Sulfur powder", 2, "Mobile electrons in metal."),
      Q("Ionic compound in solid state:", "Conducts electricity", "Ions fixed — no conduction", "Always gas", "Magnetic always", 1, "Lattice locked."),
      Q("Covalent bond is:", "Transfer", "Shared pair", "Sea of electrons", "Ion pair only", 1, "Non-metal + non-metal often."),
      Q("Simple molecular iodine:", "Very high mp", "Low mp — weak IM forces", "Metallic", "Ionic lattice", 1, "I₂ molecules."),
      Q("Graphite lubricant because:", "Ionic layers", "Weak forces between layers slide", "Gas", "Dissolves in water", 1, "Sheets slip."),
      Q("Electronegativity across period:", "Decreases", "Increases", "Constant", "Zero", 1, "Attraction for bonding e⁻."),
      Q("Polar molecule example:", "Cl₂", "HCl", "N₂", "O₂", 1, "ΔEN."),
      Q("NH₄⁺ has:", "Only ionic bonds", "Dative covalent to H⁺", "Metallic bond", "No bonds", 1, "Coordinate bond."),
      Q("MgO vs NaCl melting point:", "MgO lower", "MgO higher (stronger ionic attraction)", "Same", "Cannot compare", 1, "2+ and 2− vs 1+1−."),
      Q("Hydrogen bond in ice:", "Makes denser", "Open structure — ice floats", "No H bonds", "Only covalent", 1, "Expanded lattice."),
      Q("Metallic bonding strength affects:", "Only colour", "Melting point", "Nothing", "Only gas", 1, "Stronger bond → higher mp."),
      Q("SiO₂ structure:", "Simple molecular", "Giant covalent", "Metallic", "Ionic only", 1, "Network solid."),
      Q("Which has highest bp at 1 atm:", "CH₄", "H₂O", "Ne", "H₂", 1, "Hydrogen bonding."),
      Q("Double bond:", "Two shared pairs", "One pair", "Three pairs", "No electrons", 0, "e.g. O₂, CO₂."),
      Q("Coordinate bond in CO (concept):", "Both e⁻ from O only", "Both from C", "One from each always", "Ionic", 0, "Lone pair from O to C (A-level)."),
      Q("Van der Waals increase with:", "Smaller surface", "More electrons / larger molecule", "Higher charge only", "Ionic character", 1, "Polarisability."),
      Q("Alloy brass is:", "Pure Cu", "Cu + Zn", "Fe + C", "Na + Cl", 1, "Brass composition."),
      Q("Why metals malleable:", "Layers slide without breaking metallic bond", "Ionic shatter", "Gas", "Only gold", 0, "Sea rearranges."),
      Q("C60 is:", "Giant covalent only", "Molecular", "Ionic", "Metal", 1, "Discrete molecules."),
      Q("Bond in NaCl crystal:", "Covalent network", "Ionic", "Metallic", "Hydrogen", 1, "Electrostatic."),
      Q("Dipole-dipole vs H-bond:", "Always same", "H-bond stronger involving H-F,O,N", "Dipole always stronger", "Neither exists", 1, "H-bond special case."),
      Q("Electronegativity difference large →:", "Non-polar covalent", "Ionic character high", "No bond", "Only metal", 1, "Threshold ~1.7 rule of thumb."),
      Q("Graphite electrode use:", "Insulator", "Conductor along plane", "Only liquid", "Never", 1, "Electrons along layers."),
      Q("Boiling HCl vs HF:", "HCl higher", "HF higher (H-bonds)", "Same", "Neither boils", 1, "HF associates."),
      Q("Ceramic (ionic giant) property:", "Ductile", "Brittle", "Liquid at 25°C", "Conducts always", 1, "Shatters."),
      Q("Metallic lustre due to:", "Photon absorption/re-emission by electron sea", "Ion colour only", "Gas", "Water", 0, "Delocalised e⁻."),
      Q("Intermolecular forces in liquid Br₂:", "Covalent bonds break", "Weak IM forces between Br₂ molecules", "Ionic", "None", 1, "Molecular liquid."),
    ],
    trueFalse: [
      TF("Diamond and graphite are both pure carbon but different structures.", true, "Allotropes."),
      TF("All covalent substances have low melting points.", false, "Giant covalent exceptions."),
      TF("Ionic compounds dissolve in water by ion-dipole interaction.", true, "Hydration of ions."),
      TF("Metals conduct electricity because ions move through the lattice.", false, "Electrons move."),
      TF("Hydrogen bonding is a type of covalent bond within a water molecule.", false, "Within molecule covalent; between molecules H-bond."),
      TF("NaCl vapour contains NaCl molecules.", false, "Vapour often ion pairs/molecules at high T — O-level: lattice breaks to ions in solution/melt."),
      TF("Greater charge density on ion tends to strengthen ionic attraction.", true, "Favour smaller highly charged ions."),
      TF("Graphite has only sp³ hybridised carbons.", false, "sp² in layers."),
      TF("London dispersion forces exist between all atoms/molecules.", true, "Instantaneous dipoles."),
      TF("Triple bond stronger than single bond.", true, "More shared electrons."),
      TF("Salt bridge in cell is ionic conduction.", true, "Completes circuit."),
      TF("Metallic radius increases down group.", true, "Extra electron shell."),
    ],
  },
];
