const T3 = "Theme 3: Chemistry in a Sustainable World";

function Q(q, a, b, c, d, i, e) {
  return [q, [a, b, c, d], i, e];
}
function TF(s, ok, x) {
  return [s, ok, x];
}

const svgOrg = `<svg viewBox="0 0 320 90" xmlns="http://www.w3.org/2000/svg"><rect width="320" height="90" fill="#1c222d"/><text x="8" y="22" fill="#a78bfa" font-size="11">Alkane C–C single</text><text x="8" y="42" fill="#fb923c" font-size="11">Alkene C=C · decolourises Br₂(aq)</text><text x="8" y="62" fill="#5eead4" font-size="11">Alcohol –OH · Acid –COOH · Ester + H₂O</text></svg>`;

const t17quiz = [
  Q("Which decolourises bromine water:", "Ethane", "Ethene", "Methane", "Ethanoic acid", 1, "Addition to C=C."),
  Q("General formula alkane:", "CₙH₂ₙ", "CₙH₂ₙ₊₂", "CₙH₂ₙ₋₂", "CₙHₙ", 1, "Saturated chain."),
  Q("Product of complete combustion of C₃H₈:", "CO only", "CO₂ + H₂O", "C + H₂O", "NH₃", 1, "Hydrocarbon + O₂."),
  Q("Ester smell often:", "Rotten", "Fruity", "Sour only", "None", 1, "Characteristic."),
  Q("Oxidation of ethanol with acidified K₂Cr₂O₇:", "Ethane", "Ethanoic acid", "Ethene", "Ethyl ethanoate", 1, "–OH → –COOH."),
  Q("Cracking purpose:", "Join molecules", "Break large molecules to useful smaller ones", "Remove O₂", "Make polymers only", 1, "Petroleum refining."),
  Q("Acid + alcohol → ester catalyst:", "NaOH", "Conc H₂SO₄", "Pt", "Water", 1, "Dehydrating catalyst."),
  Q("Functional group –COOH:", "Alcohol", "Aldehyde", "Carboxylic acid", "Ester", 2, "Carboxy."),
  Q("Test for –COOH with carbonate:", "No reaction", "Fizzes CO₂", "Blue ppt", "Purple gas", 1, "Acid + carbonate."),
  Q("Addition of steam to ethene (industrial):", "Ethanol", "Ethane", "Ethanoic acid", "Polyethene", 0, "Hydration."),
  Q("Poly(ethene) from:", "Ethane", "Ethene", "Ethanol", "Ethyne", 1, "Addition polymer."),
  Q("Isomer of C₄H₁₀:", "Only one structure", "Butane / methylpropane", "Benzene", "Water", 1, "Structural isomerism."),
  Q("Incomplete combustion major toxic product:", "CO₂", "CO", "N₂", "O₃", 1, "Carbon monoxide."),
  Q("Alkene + steam → alcohol is:", "Substitution", "Addition", "Cracking", "Neutralisation", 1, "Across double bond."),
  Q("Ethanoic acid is:", "Strong acid", "Weak acid", "Alkali", "Salt", 1, "Partial ionisation."),
  Q("Acid hydrolysis of ester gives:", "Only polymer", "Carboxylic acid + alcohol", "Only water", "Salt only", 1, "Reverse esterification."),
  Q("Alkenes often sootier flame than alkanes because:", "Lower C:H", "Higher C:H ratio", "No carbon", "Only H burns", 1, "Less complete per C."),
  Q("Dehydration ethanol → ethene:", "Dilute H₂SO₄", "Conc H₂SO₄ heat", "NaOH", "Br₂", 1, "Elimination."),
  Q("Saturated hydrocarbon:", "Ethene", "Propane", "Propyne", "Benzene", 1, "Alkane saturated."),
  Q("Molecular formula ethanol:", "C₂H₄O", "C₂H₆O", "CH₄O", "C₂H₄", 1, "C₂H₅OH."),
  Q("Ethanoic acid has:", "1 C", "2 C in molecule", "6 C ring", "No O", 1, "CH₃COOH."),
  Q("Fermentation to ethanol needs:", "O₂ only", "Yeast anaerobic", "Cl₂", "Light only", 1, "Enzymes."),
  Q("Shift equilibrium to ester:", "Add excess water", "Remove water", "Cool only", "Add NaCl", 1, "Le Chatelier."),
  Q("Bromine + alkene product type:", "Dibromoalkane", "Alkane only", "Carboxylic acid", "No reaction", 0, "Addition."),
  Q("Display ethene has:", "Single C–C", "Double C=C", "Triple bond", "Ionic", 1, "Unsaturation."),
  Q("Bioethanol advantage:", "Renewable from biomass", "Zero CO₂ lifecycle always", "No land use", "Only solid", 0, "Renewable argument."),
];

export const topicsTheme3 = [
  {
    id: "17",
    theme: T3,
    title: "Alkanes, Alkenes, Alcohols, Acids, Esters",
    cheatBlocks: [
      { title: "Hydrocarbons", points: ["**Alkane** CₙH₂ₙ₊₂ — single bonds; substitution with halogen (UV).", "**Alkene** CₙH₂ₙ — C=C; addition reactions; test: **bromine water** decolourises.", "**Cracking** — long alkanes → shorter alkanes + alkenes (catalyst/heat)."] },
      { title: "Oxygen compounds", points: ["**Alcohol** — –OH; oxidised to **carboxylic acid** (acidified dichromate: orange→green).", "**Carboxylic acid** — –COOH; weak acid.", "**Ester** — acid + alcohol (conc H₂SO₄) → ester + water; fruity smell."] },
      { title: "Combustion", points: ["Complete → CO₂ + H₂O; incomplete → CO/C + lower O₂.", "Alkenes more sooty than alkanes (higher C:H ratio)."] },
    ],
    infographics: [{ svg: svgOrg, caption: "Organic families (revision)" }],
    flashcards: [
      { front: "General formula alkene?", back: "CₙH₂ₙ." },
      { front: "Test for C=C?", back: "Brown bromine water → colourless." },
      { front: "Ethanol → ethanoic acid?", back: "Oxidation." },
      { front: "Esterification?", back: "Acid + alcohol, conc H₂SO₄ catalyst." },
      { front: "Major product complete combustion propane?", back: "CO₂ + H₂O." },
      { front: "Substitution vs addition?", back: "Alkane + halogen substitution; alkene addition across double bond." },
      { front: "Functional group aldehyde?", back: "–CHO (if taught)." },
      { front: "Why alkenes more reactive?", back: "π bond weaker; electron-rich site." },
      { front: "Dehydration of ethanol?", back: "Conc H₂SO₄ → ethene + water." },
      { front: "Carboxylic acid + carbonate?", back: "Salt + CO₂ + H₂O." },
      { front: "Naming C₄H₁₀ isomers?", back: "Butane vs methylpropane." },
      { front: "Display formula shows?", back: "All bonds explicitly." },
      { front: "PVC monomer?", back: "Chloroethene." },
      { front: "Natural gas main alkane?", back: "Methane." },
    ],
    quiz: t17quiz,
    trueFalse: [
      TF("All alkenes have the same empirical formula CH₂.", true, "CₙH₂ₙ → CH₂."),
      TF("Alkanes undergo addition with bromine water readily.", false, "Substitution with Br₂ under UV; no decolourisation with bromine water like alkenes."),
      TF("Esters are formed in a condensation reaction with water eliminated.", true, "Esterification."),
      TF("Ethanol is oxidised to ethanal then ethanoic acid with strong oxidant in lab.", true, "Intermediate aldehyde if distilled off."),
      TF("Complete combustion always gives only CO₂.", false, "Also H₂O for hydrocarbons."),
      TF("PVC is an addition polymer of chloroethene.", true, "Vinyl chloride."),
      TF("Carboxylic acids turn blue litmus red.", true, "Acidic."),
      TF("Alkenes are unsaturated.", true, "Can add more atoms."),
      TF("Methane is tetrahedral.", true, "sp³ carbon."),
      TF("Ethanoic acid reacts with NaOH to form sodium ethanoate.", true, "Neutralisation."),
      TF("Hydrogenation of vegetable oils uses nickel catalyst.", true, "Hardening fats."),
      TF("Isomers have different molecular formulas.", false, "Same molecular formula, different structure."),
    ],
  },
  {
    id: "18",
    theme: T3,
    title: "Polymers",
    cheatBlocks: [
      { title: "Addition polymerisation", points: ["Monomer: **alkene** with C=C opens.", "Repeat unit in brackets; **n** large.", "e.g. poly(ethene), PVC, PTFE."] },
      { title: "Condensation", points: ["**Nylon** (polyamide) — amide link; **polyester** (Terylene) — ester link.", "Small molecule eliminated (often H₂O)."] },
      { title: "Sustainability", points: ["Plastics persist; **recycling** codes; **biodegradable** vs durable.", "Microplastics environmental issue."] },
    ],
    flashcards: [
      { front: "Repeat unit?", back: "Smallest repeating section in brackets." },
      { front: "Nylon link?", back: "Amide (–CONH–)." },
      { front: "Polyester link?", back: "Ester." },
      { front: "Monomer polypropene?", back: "Propene." },
      { front: "Thermoplastic vs thermoset?", back: "Thermoplastic remelts; thermoset cross-linked rigid." },
      { front: "Why plastic waste problem?", back: "Slow degradation; fossil-derived." },
      { front: "Biopolymer example?", back: "Starch, cellulose (natural polymers)." },
      { front: "Condensation vs addition polymer?", back: "Condensation eliminates small molecule." },
      { front: "Terylene type?", back: "Synthetic polyester fibre." },
      { front: "Plasticiser?", back: "Softens PVC chains." },
      { front: "Cross-linking effect?", back: "Harder, less flexible." },
      { front: "Recycling symbol meaning?", back: "Resin identification — sorting." },
      { front: "Addition polymer only C,H,Cl etc.?", back: "No atoms lost from monomer." },
      { front: "Polystyrene monomer?", back: "Phenylethene (styrene)." },
    ],
    quiz: [
      Q("Poly(ethene) monomer:", "Ethane", "Ethene", "Ethanol", "Ethyne", 1, "Opens double bond."),
      Q("Condensation polymer examples:", "Only PE", "Nylon, polyester", "Only diamond", "NaCl", 1, "Step-growth."),
      Q("PVC from:", "Ethene", "Chloroethene", "Benzene", "Propane", 1, "Vinyl chloride."),
      Q("Repeat unit drawn with:", "Only ions", "Brackets and continuation bonds", "Circles", "No bonds", 1, "Show backbone."),
      Q("Nylon formed from:", "Ethene only", "Diamine + diacid (or derivatives)", "Glucose only", "HCl", 1, "Condensation."),
      Q("Polyester from:", "Two alcohols", "Diol + diacid", "Metal + acid", "Only ethene", 1, "Ester links."),
      Q("Thermosetting polymer:", "Remelts easily", "Cross-linked — does not remelt", "Only gas", "Ionic", 1, "Network."),
      Q("Microplastics:", "Large bottles only", "Small plastic fragments", "Only metal", "Water vapour", 1, "Environmental concern."),
      Q("Addition polymer M_r change n monomers:", "Loses H₂O each step", "Sum of monomers (no small molecule out)", "Halves", "Becomes ionic", 1, "Mass adds."),
      Q("Natural polymer:", "PVC", "Cellulose", "Polyethene", "Nylon", 1, "Plant polymer."),
      Q("Why recycle plastics:", "Reduce landfill and crude oil use", "Increase waste", "No reason", "Make heavier", 0, "Sustainability."),
      Q("PTFE monomer:", "Tetrafluoroethene", "Ethene", "Propene", "Styrene", 0, "CF₂=CF₂."),
      Q("Plasticiser in PVC:", "Increases chain sliding", "Cross-links fully", "Removes Cl", "Only colour", 0, "Flexibility."),
      Q("Biodegradable plastic (ideal):", "Never breaks", "Microbes break down", "Infinite life", "Metal", 1, "Design goal."),
      Q("Polypeptide (protein) is:", "Addition polymer of ethene", "Condensation of amino acids", "Ionic crystal", "Only fat", 1, "Amide links."),
      Q("Transesterification in biodiesel:", "Ester exchange", "Addition", "Only cracking", "Neutralisation", 0, "Context."),
      Q("Monomer count in repeat unit of poly(ethene):", "2", "1 (–CH₂–CH₂–) derived from 1 ethene", "3", "0", 1, "One monomer unit."),
      Q("Condensation needs:", "Always UV", "Two functional monomers often", "Only heat no monomer", "Diamond", 1, "Two sites."),
      Q("Foam polystyrene:", "Gas pockets in polymer", "Pure metal", "Liquid only", "Salt", 0, "Expanded PS."),
      Q("Elastomer:", "Rigid glass", "Cross-linked rubber — stretches", "Only ceramic", "Gas", 1, "Elastic."),
      Q("HDPE vs LDPE:", "Same branching", "Different densities/branching", "Not polymers", "Only gases", 1, "Structure."),
      Q("Depolymerisation:", "Break polymer to monomers", "Make longer chains", "Only physical", "Ionise", 0, "Reverse."),
      Q("Green polymer goal:", "Non-recyclable", "Renewable feedstock + recyclable", "Only black colour", "Heavy metal only", 1, "Sustainable chemistry."),
      Q("Kevlar® type:", "Polyamide fibre", "Polyethene", "Salt", "Alkane", 0, "Strong aromatic polyamide."),
      Q("Phthalates context:", "Plasticisers", "Monomers for PE", "Catalysts only", "Fuels", 0, "Softeners."),
      Q("Combustion of PVC releases:", "Only N₂", "HCl among products", "No gases", "He only", 1, "Chlorinated polymer."),
      Q("Oxo-biodegradable (debated):", "Proven harmless always", "Fragmentation + controversy", "Never fragments", "Only metal", 1, "Environmental nuance."),
    ],
    trueFalse: [
      TF("All plastics are addition polymers.", false, "Condensation: nylon, polyester."),
      TF("The repeat unit of poly(propene) has a methyl branch on every other carbon.", true, "CH₃ side group."),
      TF("Thermoplastics can be remoulded when heated.", true, "No extensive cross-links."),
      TF("Nylon can be made from diamine and diacyl chloride.", true, "Lab nylon rope trick."),
      TF("PET is a polyester used in bottles.", true, "Polyethylene terephthalate."),
      TF("Burning plastics in open air is always environmentally safe.", false, "Toxic gases, particulates."),
      TF("Polymers have very high molecular masses.", true, "Macromolecules."),
      TF("Monomer and repeat unit are always identical formula.", false, "Condensation loses atoms."),
      TF("Recycling reduces crude oil demand for new plastic.", true, "Feedstock saving."),
      TF("Bioplastics are always biodegradable.", false, "Some are durable PLA etc."),
      TF("Cross-linked rubber is vulcanised with sulfur.", true, "Historical process."),
      TF("Polymer burning test: PE drips; PVC self-extinguishing green flame (Cl).", true, "Qualitative distinction."),
    ],
  },
  {
    id: "19",
    theme: T3,
    title: "Maintaining Air Quality",
    cheatBlocks: [
      { title: "Pollutants", points: ["**CO** — incomplete combustion; toxic (binds haemoglobin).", "**SO₂, NOₓ** — acid rain; from fossil fuel **S** and **high T N₂+O₂** in engines.", "**Particulates** — PM₂.₅, respiratory.", "**CFCs** historic **ozone** depletion — **Montreal Protocol**."] },
      { title: "Greenhouse", points: ["**CO₂, CH₄, N₂O, H₂O vapour** trap IR.", "**Climate change** — linked to enhanced greenhouse effect.", "Mitigation: renewables, efficiency, transport (policy context)."] },
      { title: "Control", points: ["**Catalytic converter**: CO + hydrocarbons → CO₂ + H₂O; NOₓ → N₂.", "**Flue gas desulfurisation** in power stations.", "**Electric vehicles** reduce local NOₓ/PM (tailpipe)."] },
    ],
    flashcards: [
      { front: "Main anthropogenic greenhouse gas emphasis?", back: "CO₂ from fossil fuels." },
      { front: "Acid rain from?", back: "SO₂, NOₓ → H₂SO₄, HNO₃ in rain." },
      { front: "Ozone layer location?", back: "Stratosphere — UV-B absorption." },
      { front: "CO poisoning?", back: "Binds Hb stronger than O₂." },
      { front: "Photochemical smog?", back: "NOₓ + VOCs + sunlight → O₃ at ground level." },
      { front: "Montreal Protocol?", back: "Phase out ozone-depleting substances." },
      { front: "Indoor air: radon?", back: "Radioactive gas from rocks." },
      { front: "Lead in petrol (historical)?", back: "Neurotoxic — largely phased out." },
      { front: "Carbon monoxide colour?", back: "Odourless colourless — dangerous." },
      { front: "Why NO in car engine?", back: "N₂ + O₂ at high T." },
      { front: "Afforestation?", back: "CO₂ sink (partial)." },
      { front: "Methane source?", back: "Rice, livestock, landfill, natural gas leaks." },
      { front: "Paris Agreement aim?", back: "Limit warming — national pledges." },
      { front: "Scrubber removes?", back: "SO₂ from flue gases." },
    ],
    quiz: [
      Q("CO is harmful because:", "Acidifies blood only", "Blocks O₂ transport in blood", "Radioactive", "Green", 1, "Hb affinity."),
      Q("Acid rain damages:", "Only metals", "Buildings, aquatic life, forests", "Nothing", "Only plastics", 1, "Low pH."),
      Q("CFCs harm ozone by:", "Adding O₂", "Releasing Cl radicals that catalyse O₃ destruction", "Absorbing all UV", "Making rain", 1, "Chain reaction."),
      Q("Greenhouse effect is:", "No IR absorption", "Certain gases trap outgoing IR", "Only visible light block", "Ozone only", 1, "Thermal balance."),
      Q("Catalytic converter reduces:", "Only CO₂", "CO, unburnt HC, NOₓ", "O₂", "N₂ only", 1, "Three-way cat."),
      Q("SO₂ mainly from:", "Only volcanoes", "Burning fossil fuels with sulfur", "Photosynthesis", "O₃", 1, "Coal/oil."),
      Q("Ground-level O₃:", "Always good", "Smog component — respiratory irritant", "Stratosphere only", "Inert", 1, "Bad at surface."),
      Q("PM₂.₅ means:", "Particles ≤2.5 µm", "Pressure", "Only gas", "Metal only", 0, "Fine particulates."),
      Q("Incomplete combustion of hydrocarbon produces:", "Only CO₂", "CO and/or C", "Only H₂", "O₃", 1, "Limited O₂."),
      Q("CH₄ GWP vs CO₂ (concept):", "Lower per molecule", "Higher over 20-yr", "Zero", "Same always", 1, "Potent GHG."),
      Q("Electric car local benefit:", "Less tailpipe NOₓ in city", "No energy use", "Removes all PM", "No grid impact", 0, "Point of use."),
      Q("Flue gas desulfurisation:", "Adds sulfur", "Removes SO₂", "Makes CO", "Only water", 1, "Wet scrubbing."),
      Q("Indoor pollutant:", "Only O₂", "Formaldehyde from furniture VOCs", "Only N₂", "Helium", 1, "VOCs."),
      Q("Stratospheric O₃ protects from:", "IR", "UV-B", "Visible all", "Sound", 1, "DNA damage."),
      Q("NOₓ from lightning:", "Never", "Natural source", "Only human", "Only liquid", 1, "Natural fixation."),
      Q("Carbon capture (concept):", "Emit more CO₂", "Store CO₂ from industry", "Remove N₂", "Burn coal more", 1, "CCS."),
      Q("Eutrophication linked to air via:", "Only CO", "NOₓ deposition → nitrate in water", "Only O₃", "Argon", 1, "Nutrient runoff also major."),
      Q("Lead historically in petrol:", "Catalyst", "Antiknock", "Coolant", "Fuel", 1, "Tetraethyl lead."),
      Q("WHO air quality guidelines:", "Legal everywhere", "Health-based targets", "Ignore PM", "Only CO₂", 1, "Guidance."),
      Q("Wildfire smoke:", "Only CO₂", "PM and CO among pollutants", "Pure O₂", "Helium", 1, "Complex mix."),
      Q("Hydrofluorocarbons vs CFCs:", "Same ozone impact", "Lower ODP but often high GWP", "No GWP", "Not gases", 1, "Trade-offs."),
      Q("Urban heat island:", "Rural warmer", "City warmer than surroundings", "Same T", "Only winter", 1, "Concrete, less evapo."),
      Q("Ocean acidification:", "CO₂ → lower pH seawater", "SO₂ only", "No change", "Only freshwater", 0, "H⁺ from CO₂."),
      Q("Mask effectiveness vs PM₂.₅:", "Cloth stops all", "N95 better than loose cloth", "No filter works", "Only outdoors", 1, "Filtration rating."),
      Q("Renewable vs fossil CO₂ argument:", "Same always", "Biomass short-cycle may be nearer carbon neutral", "No CO₂ from biomass burn", "Coal is renewable", 1, "Lifecycle nuance."),
      Q("Air Quality Index combines:", "Only temperature", "Several pollutants into index", "Only noise", "Only humidity", 1, "Composite."),
      Q("Deforestation and climate:", "Removes CO₂ sink", "Adds O₃ layer", "Cools planet always", "No effect", 0, "Less uptake."),
    ],
    trueFalse: [
      TF("Stratospheric ozone is a pollutant in the same sense as ground-level ozone.", false, "Location matters."),
      TF("Complete combustion of hydrocarbon in excess O₂ gives CO₂ and H₂O.", true, "Stoichiometric excess O₂."),
      TF("All greenhouse gases are toxic to breathe.", false, "CO₂ in air is normal; toxicity at high concentration."),
      TF("Montreal Protocol helped the ozone layer recover.", true, "Success story."),
      TF("NO₂ is brownish and contributes to acid rain.", true, "Visible in smog."),
      TF("Carbon monoxide has a sharp smell.", false, "Odourless."),
      TF("Sulfur in diesel/fuel oil contributes to SO₂ emissions.", true, "S content."),
      TF("Catalytic converters work best when hot.", true, "Light-off temperature."),
      TF("Air pollution only affects lungs.", false, "Cardiovascular, developmental effects."),
      TF("CO₂ is the only greenhouse gas.", false, "CH₄, N₂O, CFCs, H₂O vapour."),
      TF("Acid rain pH can be below 5.6 (natural rain weakly acidic from CO₂).", true, "Anthropogenic lower."),
      TF("Venus extreme greenhouse is mainly CO₂ thick atmosphere.", true, "Runaway comparison."),
    ],
  },
];
