const T2 = "Theme 2: Chemical Reactions";

function Q(q, a, b, c, d, i, e) {
  return [q, [a, b, c, d], i, e];
}
function TF(s, ok, x) {
  return [s, ok, x];
}

const svgPh = `<svg viewBox="0 0 300 90" xmlns="http://www.w3.org/2000/svg"><rect width="300" height="90" fill="#1c222d"/><defs><linearGradient id="phg" x1="0%" x2="100%"><stop offset="0%" stop-color="#ef4444"/><stop offset="50%" stop-color="#eab308"/><stop offset="100%" stop-color="#3b82f6"/></linearGradient></defs><rect x="20" y="30" width="260" height="20" rx="6" fill="url(#phg)"/><text x="22" y="22" fill="#8b95a8" font-size="9">acid 0</text><text x="135" y="22" fill="#8b95a8" font-size="9">7</text><text x="240" y="22" fill="#8b95a8" font-size="9">alkali 14</text></svg>`;

const svgEl = `<svg viewBox="0 0 280 120" xmlns="http://www.w3.org/2000/svg"><rect width="280" height="120" fill="#1c222d"/><rect x="50" y="35" width="180" height="55" fill="#2a3344" stroke="#5eead4"/><rect x="60" y="45" width="35" height="35" fill="#6366f1"/><rect x="185" y="45" width="35" height="35" fill="#f87171"/><text x="58" y="100" fill="#8b95a8" font-size="9">cathode −</text><text x="175" y="100" fill="#8b95a8" font-size="9">anode +</text><text x="70" y="28" fill="#5eead4" font-size="10">Electrolysis · DC supply</text></svg>`;

export const topicsTheme2 = [
  {
    id: "6", theme: T2, title: "Chemical Calculations",
    cheatBlocks: [{ title: "Moles", points: ["n = mass/Mr; Mr from periodic table.", "Avogadro 6.02×10²³ particles per mole.", "Gas: n = V/24 dm³ at r.t.p. (syllabus).", "Solution: n = C×V (V in dm³)."] }, { title: "Stoichiometry", points: ["Balance equation → mole ratio.", "Limiting reactant stops reaction.", "% yield = actual/theoretical ×100.", "Empirical vs molecular formula."] }],
    flashcards: [{ front: "n from mass?", back: "mass ÷ Mr" }, { front: "Concentration units mol/dm³", back: "Molarity C." }, { front: "Molar gas volume r.t.p.", back: "24 dm³/mol." }, { front: "Limiting reactant?", back: "Used up first." }, { front: "Empirical formula?", back: "Simplest ratio." }, { front: "Water of crystallisation?", back: "H₂O in lattice (e.g. CuSO₄·5H₂O)." }, { front: "Titre?", back: "Volume of solution in titration to endpoint." }, { front: "Concordant titres?", back: "Within 0.1–0.2 cm³." }, { front: "Back titration idea?", back: "Add excess then titrate remainder." }, { front: "Atom economy?", back: "(mass desired / mass all products)×100." }, { front: "Mole fraction (adv)?", back: "nᵢ/n_total." }, { front: "Standard solution?", back: "Known concentration." }, { front: "Dilution C₁V₁=C₂V₂?", back: "Same moles before/after dilution." }, { front: "Relative formula mass CaCO₃?", back: "40+12+48=100." }],
    quiz: [
      Q("Mr H₂SO₄ (H1,S32,O16):", "82", "88", "98", "108", 2, "2+32+64."),
      Q("Moles in 9 g water:", "0.25", "0.5", "1", "2", 1, "9/18=0.5."),
      Q("Volume 0.25 mol gas at r.t.p.:", "6 dm³", "12 dm³", "24 dm³", "4 dm³", 0, "0.25×24=6."),
      Q("Moles in 100 cm³ of 2 mol/dm³ HCl:", "0.2", "0.02", "2", "0.5", 0, "0.1×2=0.2."),
      Q("Mass of 0.5 mol NaOH (Mr 40):", "10 g", "20 g", "40 g", "80 g", 1, "0.5×40."),
      Q("Empirical formula CH₂O molecular 180:", "CH₂O", "C₆H₁₂O₆", "C₂H₄O₂", "C₃H₆O₃", 1, "Factor 6."),
      Q("%O in CO₂ by mass:", "~27%", "~44%", "~73%", "~50%", 2, "32/44."),
      Q("Limiting: 2H₂+O₂→2H₂O; 3 mol H₂, 2 mol O₂:", "H₂ limiting", "O₂ limiting", "Neither", "Both", 0, "Need 1.5 mol O₂ for 3H₂."),
      Q("Theoretical mass CaCO₃ from 0.1 mol:", "5 g", "10 g", "100 g", "1 g", 1, "0.1×100."),
      Q("Dilute 50 cm³ 2M to 500 cm³ final:", "0.1 M", "0.2 M", "2 M", "0.02 M", 1, "C₂=0.1×2/1."),
      Q("Atoms in 1 mol CO₂:", "3×6.02×10²³", "6.02×10²³", "2×6.02×10²³", "1", 0, "3 atoms per molecule."),
      Q("Mass same moles N₂ vs O₂:", "N₂ heavier", "O₂ heavier", "Same", "Cannot", 1, "Mr 32>28."),
      Q("Stoichiometry Fe₂O₃+3CO→2Fe+3CO₂: 80 g Fe₂O₃ (Mr160):", "1 mol Fe₂O₃", "0.5 mol", "2 mol", "0.25 mol", 0, "80/160."),
      Q("Fe produced from 0.5 mol Fe₂O₃:", "28 g", "56 g", "112 g", "84 g", 1, "1 mol Fe per 0.5 mol oxide → 56g."),
      Q("Actually 50g Fe, theoretical 56g, % yield:", "~89%", "100%", "50%", "112%", 0, "50/56."),
      Q("Concentration mol/dm³ definition:", "mol per litre", "g per litre", "mol per cm³ only", "pH", 0, "mol dm⁻³."),
      Q("Number of molecules in 44 g CO₂:", "6.02×10²³", "2×6.02×10²³", "0.5×6.02×10²³", "3×6.02×10²³", 0, "1 mol."),
      Q("Hydrated CuSO₄·5H₂O anhydrous part Mr:", "160", "250", "90", "18", 0, "CuSO₄."),
      Q("Titration: 25 cm³ 0.1M acid neutralised by 0.1M alkali volume:", "25 cm³ (mono-mono)", "50 cm³", "12.5 cm³", "100 cm³", 0, "1:1 mole if monoprotic."),
      Q("Excess reagent after reaction:", "Gone", "Left over", "Catalyst", "Product", 1, "Not fully consumed."),
      Q("Mole ratio N₂+3H₂→2NH₃ for 4 mol NH₃ needs N₂:", "1", "2", "3", "4", 1, "2 mol N₂."),
      Q("ppm to very dilute (concept):", "parts per million", "pressure", "only solid", "mole only", 0, "Trace concentration."),
      Q("Back titration used when:", "Direct titration impossible", "Always faster", "No indicator", "Only gas", 0, "Slow direct reaction."),
      Q("Atom economy high means:", "More waste", "More desired in product mass", "No reaction", "Low yield", 1, "Green metric."),
      Q("Volume 2 mol gas r.t.p.:", "12 dm³", "24 dm³", "48 dm³", "6 dm³", 2, "2×24."),
      Q("0.01 mol electron charge (Faraday context qual):", "Proportional to moles at electrode", "Fixed 1 C", "Zero", "Only gas", 0, "Q=nF."),
    ],
    trueFalse: [TF("One mole always occupies 24 dm³.", false, "Only ideal gas at r.t.p.; liquids/solids differ."), TF("Mr has units kg.", false, "Dimensionless relative mass."), TF("Balanced equation conserves atoms.", true, "Conservation of mass."), TF("Yield can exceed 100%.", false, "Usually error or wet product."), TF("Dilution increases concentration.", false, "Decreases."), TF("Avogadro's law: equal volumes of gases same moles at same T,P.", true, "Ideal gases."), TF("Water Mr = 18.", true, "H₂O."), TF("Empirical formula can equal molecular.", true, "e.g. H₂O."), TF("Titre must be read from bottom of meniscus.", true, "For colourless liquids."), TF("Primary standard must be stable and pure.", true, "Titration standard."), TF("Mole ratio from equation is for moles not grams directly.", true, "Convert via Mr."), TF("Concentration × volume gives moles only if V in dm³.", true, "Unit check.")],
  },
  {
    id: "7", theme: T2, title: "Acids and Bases",
    cheatBlocks: [{ title: "Acids", points: ["pH<7; H⁺ in water; litmus red.", "With reactive metal → H₂; carbonate → CO₂.", "Strong: HCl, H₂SO₄, HNO₃ fully ionised (dilute)."] }, { title: "Bases", points: ["Alkali: soluble base; pH>7; OH⁻.", "Neutralisation: acid+base→salt+H₂O.", "NH₄⁺ salt + alkali → NH₃ gas."] }],
    infographics: [{ svg: svgPh, caption: "pH scale" }],
    flashcards: [{ front: "Strong vs weak acid?", back: "Strong fully ionises; weak partial." }, { front: "Alkali + NH₄Cl warmed?", back: "NH₃ gas." }, { front: "Universal indicator neutral?", back: "~Green pH7." }, { front: "Basic oxide + acid?", back: "Salt + water." }, { front: "Amphoteric Al oxide?", back: "Reacts acid and alkali." }, { front: "Conjugate pair?", back: "Acid/base differ by H⁺." }, { front: "Dilution strong acid pH?", back: "Rises toward 7." }, { front: "Indicator endpoint?", back: "Colour change complete reaction." }, { front: "Sulfuric diprotic?", back: "2 H⁺ per molecule (stepwise)." }, { front: "Ethanoic weak?", back: "Partial dissociation." }, { front: "pH + pOH = 14 (25°C)?", back: "In water Kw=10⁻¹⁴." }, { front: "Corrosive warning?", back: "Concentrated acids/alkalis." }, { front: "Farm lime?", back: "Ca(OH)₂ neutralises acid soil." }, { front: "Antacid?", back: "Weak base neutralises stomach acid." }],
    quiz: [
      Q("pH of 0.1 M NaOH strong:", "~1", "~7", "~13", "~0", 2, "High OH⁻."),
      Q("Mg + dil HCl:", "Cl₂", "H₂", "O₂", "N₂", 1, "Metal+acid."),
      Q("Na₂CO₃ + HCl:", "No gas", "CO₂", "SO₂", "H₂", 1, "Carbonate+acid."),
      Q("Which weak acid:", "HCl", "CH₃COOH", "H₂SO₄", "HNO₃", 1, "Ethanoic."),
      Q("Neutralisation products acid+NaOH:", "Salt+CO₂", "Salt+H₂O", "Only water", "Cl₂", 1, "Classic."),
      Q("NH₃ aqueous:", "Strong acid", "Weak alkali", "Strong alkali", "Neutral", 1, "NH₄OH equilibrium."),
      Q("Indicator phenolphthalein acid:", "Pink", "Colourless", "Yellow", "Blue", 1, "Colourless in acid."),
      Q("Proton donor (Brønsted) acid:", "Accepts H⁺", "Donates H⁺", "Donates e⁻", "Accepts e⁻", 1, "Definition."),
      Q("Metal oxide CuO + H₂SO₄:", "H₂", "CuSO₄+H₂O", "SO₂", "No reaction", 1, "Basic oxide."),
      Q("Diluting acid safely:", "Water to acid", "Acid to water", "Both fast", "No water", 1, "Exothermic."),
      Q("pH of pure water 25°C:", "0", "7", "14", "1", 1, "Neutral."),
      Q("Excess stomach acid treated with:", "Strong NaOH drink", "Mild antacid", "Conc HCl", "Sugar", 1, "Weak base."),
      Q("H⁺ concentration pH=2:", "0.01 M", "0.1 M", "1 M", "0.001 M", 0, "10⁻²."),
      Q("Salt from HCl + KOH:", "KCl", "K₂SO₄", "KNO₃", "K₂CO₃", 0, "Chloride."),
      Q("Not a base:", "NaOH", "KOH", "HCl", "Ca(OH)₂", 2, "Acid."),
      Q("Alkali turns litmus:", "Red", "Blue", "No change", "Green only", 1, "Base."),
      Q("Conjugate base of H₂SO₄ (first step):", "HSO₄⁻", "SO₄²⁻", "H₃O⁺", "OH⁻", 0, "Lost one H⁺."),
      Q("Buffer (simple):", "Weak acid + conjugate salt", "Strong only", "Only NaCl", "Only water", 0, "Resists pH change."),
      Q("Acid rain pH:", ">7", "<5.6 often", "14", "Always 7", 1, "Acidic deposition."),
      Q("Zn + CH₃COOH vs HCl same conc rate:", "Same", "HCl faster (stronger)", "Acetic faster", "No Zn reaction", 1, "Higher [H⁺] in strong."),
      Q("Basic gas:", "HCl", "NH₃", "CO₂", "SO₂", 1, "Ammonia."),
      Q("Titration strong acid-strong base endpoint pH:", "~7", "~5", "~9", "~1", 0, "NaCl solution."),
      Q("Methyl orange in acid:", "Yellow", "Red", "Blue", "Pink", 1, "Red acidic."),
      Q("Sulfuric acid formula:", "H₂SO₃", "H₂SO₄", "HSO₄", "SO₂", 1, "Diprotic acid."),
      Q("Insoluble base + acid salt prep:", "Filter excess solid", "Distil", "Burn", "Only titrate", 0, "Excess oxide/carbonate."),
      Q("Water acts as acid toward NH₃:", "Never", "Donates H⁺ to NH₃", "Only gas", "Only solid", 1, "NH₄⁺ forms."),
    ],
    trueFalse: [TF("All alkalis are soluble.", false, "Alkali = soluble base; many bases insoluble."), TF("pH is log scale; pH 3 has 10× [H⁺] of pH4.", true, "Log₁₀."), TF("Neutralisation is only acid + metal.", false, "Acid + base/alkali/carbonate."), TF("Concentrated sulfuric is dehydrating agent.", true, "Removes water."), TF("NH₄⁺ is acidic in solution.", true, "Hydrolysis."), TF("Every salt solution is pH 7.", false, "Hydrolysis of ions."), TF("Indicators are weak acids/bases.", true, "Partial dissociation."), TF("Strong acid always has lower pH than weak at same concentration.", true, "Higher [H⁺]."), TF("Metal below H in series still reacts with oxidising acids differently.", true, "Cu + conc HNO₃ context."), TF("Al₂O₃ is only basic.", false, "Amphoteric."), TF("Dilute HNO₃ + Cu:", "No simple H₂", true, "Nitric oxidises."), TF("Kw increases with temperature.", true, "Endothermic ionisation of water.")],
  },
  {
    id: "8", theme: T2, title: "Salts",
    cheatBlocks: [{ title: "Preparation", points: ["Soluble salt + insoluble base/carbonate: acid + excess solid, filter, crystallise.", "Acid+alkali both soluble: **titration** then evaporate.", "Insoluble salt: **precipitation** (mix ions)."] }, { title: "Examples", points: ["AgCl white ppt; BaSO₄ white.", "CuSO₄·5H₂O blue crystals hydrated."] }],
    flashcards: [{ front: "Titration for?", back: "Two soluble reactants." }, { front: "AgNO₃ + NaCl?", back: "AgCl white ppt." }, { front: "Nitric + copper oxide?", back: "Copper nitrate + water." }, { front: "Hydrated salt?", back: "Contains water of crystallisation." }, { front: "Anhydrous copper sulfate?", back: "White; turns blue with water." }, { front: "Pb(NO₃)₂ + KI?", back: "Yellow PbI₂ ppt." }, { front: "Soluble group 1 salts?", back: "Most nitrates, group 1 salts soluble." }, { front: "Filtration after reaction?", back: "Remove excess insoluble reactant." }, { front: "Evaporate to point of crystallisation?", back: "Then cool for crystals." }, { front: "Insoluble salt prep?", back: "Double decomposition in solution." }, { front: "Zinc + H₂SO₄ excess Zn?", back: "ZnSO₄ + H₂; filter Zn." }, { front: "Ammonium sulfate fertiliser?", back: "From NH₃ + H₂SO₄." }, { front: "Fe + dilute HCl?", back: "FeCl₂ + H₂" }, { front: "Test for sulfate?", back: "Ba²⁺ acidified white ppt." }],
    quiz: [
      Q("NaCl from HCl+NaOH:", "Excess CuO", "Titration", "Burn Na", "AgCl only", 1, "Both soluble."),
      Q("AgCl from:", "Na+Cl heat", "AgNO₃+NaCl aq", "Ag+Cl₂ gas", "Only solid", 1, "Precipitation."),
      Q("CuO + H₂SO₄ excess CuO:", "Filter then crystallise", "Only filter gas", "Distil Cu", "No salt", 0, "Remove excess oxide."),
      Q("Insoluble CaCO₃ + HCl:", "CaCl₂ + CO₂ + H₂O", "Ca only", "Cl₂", "No reaction", 0, "Carbonate+acid."),
      Q("Barium test for sulfate acidified to avoid:", "CO₃²⁻ interference", "Na⁺", "Colour", "Heat", 0, "BaCO₃ also ppt."),
      Q("Hydrated salt formula dot means:", "Covalent only", "Water in crystal", "Gas", "Charge", 1, "Water of crystallisation."),
      Q("Pb²⁺ + I⁻:", "Soluble", "Yellow ppt", "Gas", "Blue", 1, "PbI₂."),
      Q("Soluble salt from insoluble carbonate:", "Add acid to excess carbonate", "Only water", "Electrolysis", "Burn", 0, "Filter excess."),
      Q("Fe + H₂SO₄:", "Fe₂(SO₄)₃ + H₂", "FeSO₄ + H₂", "S only", "No reaction", 1, "Iron(II) with dilute."),
      Q("NH₃ + H₂SO₄:", "(NH₄)₂SO₄", "NH₄OH", "N₂", "H₂", 0, "Salt."),
      Q("Which pair gives soluble salt both ions Na+Cl:", "Precipitation", "Evaporate titration product", "Only fusion", "Decant oil", 1, "Titration route."),
      Q("KNO₃ solubility vs temperature:", "Decreases", "Increases strongly", "Constant", "Zero", 1, "Often crystallise on cooling."),
      Q("Washing crystals:", "With saturated solution of same salt", "Distilled always full", "Hot acid", "Oil", 0, "Reduce loss."),
      Q("ZnCl₂ from Zn + HCl:", "Crystallise", "Only gas collect", "No product", "Burn Zn", 0, "Evaporate."),
      Q("Silver sulfate solubility:", "Insoluble like AgCl", "Soluble unlike AgCl", "Gas", "Only molten", 1, "AgCl insoluble."),
      Q("Mg + HNO₃ dilute may:", "Still complex", "H₂ sometimes with very dilute Mg", "Never react", "Only NO₂ always", 1, "Syllabus: Mg+HCl typical."),
      Q("Salt hydrolysis Na₂CO₃ solution:", "Acidic", "Basic", "Always 7", "Neutral", 1, "CO₃²⁻ hydrolysis."),
      Q("Double salt (context):", "Two cations/anions one crystal", "Only one ion", "Gas", "No crystal", 0, "Alum type."),
      Q("Efflorescence:", "Salt loses water to air", "Gains water", "Melts", "Explodes", 0, "Drying out."),
      Q("Deliquescent:", "Absorbs water to dissolve", "Loses water", "Inert", "Only gas", 0, "CaCl₂."),
      Q("Preservative NaCl:", "Osmosis bacteria", "pH 14", "Oxidises all", "Only sweet", 0, "Food context."),
      Q("Epsom salt:", "MgSO₄·7H₂O", "NaCl", "CaCO₃", "KNO₃", 0, "Hydrated sulfate."),
      Q("Fertiliser nitrate benefit:", "N for protein", "Only P", "Only K", "Cl only", 0, "N source."),
      Q("Chloride test acidified AgNO₃:", "White AgCl", "Black", "Red", "Gas", 0, "Except AgBr/I."),
      Q("Sulfite + acid:", "SO₂ gas", "CO₂ only", "H₂", "No gas", 0, "Acidified sulfite."),
      Q("Complex ion [Cu(NH₃)₄]²⁺ colour:", "Deep blue solution", "Colourless", "Green ppt only", "Yellow", 0, "Excess NH₃."),
    ],
    trueFalse: [TF("All nitrates are soluble.", true, "General rule."), TF("All silver salts are insoluble.", false, "AgNO₃ soluble."), TF("Titration indicator chosen to change at steep pH jump.", true, "Endpoint near equivalence."), TF("Heating CuSO₄·5H₂O strongly gives white anhydrous.", true, "Water driven off."), TF("BaSO₄ is safe as X-ray contrast (insoluble).", true, "Medical context."), TF("Pb²⁺ salts are often toxic.", true, "Heavy metal."), TF("Filtrate is always pure product.", false, "May need crystallisation."), TF("Mixed two solutions always gives ppt.", false, "Need insoluble product."), TF("Ammonium salts all soluble.", true, "General pattern."), TF("Fe³⁺ + OH⁻ brown ppt.", true, "Fe(OH)₃."), TF("Carbonate + acid always produces CO₂.", true, "With acid protonation."), TF("Evaporating to dryness may decompose nitrates.", true, "Heat carefully.")],
    orderGame: ["Weigh acid/alkali", "Add indicator", "Titrate to endpoint", "Repeat for concordant titre", "Calculate known concentration", "Evaporate to crystallise"],
    orderTitle: "Soluble salt via titration",
  },
  {
    id: "9", theme: T2, title: "Ammonia",
    cheatBlocks: [{ title: "Haber", points: ["N₂+3H₂⇌2NH₃; Fe catalyst; ~450°C; high P.", "Recycle unreacted gases.", "NH₃ → HNO₃, fertilisers."] }, { title: "Properties", points: ["Alkaline gas; turns damp red litmus blue.", "Very soluble; fountain experiment.", "NH₄⁺ + OH⁻ → NH₃."] }],
    flashcards: [{ front: "Haber catalyst?", back: "Iron." }, { front: "Ostwald (context)?", back: "NH₃ → NO → HNO₃." }, { front: "Urea formula?", back: "CO(NH₂)₂ fertiliser N." }, { front: "Liquid NH₃ use?", back: "Refrigerant; solvent." }, { front: "Test ammonium ion?", back: "NaOH heat, gas turns litmus blue." }, { front: "Dilute NH₃ + Cu²⁺?", back: "Pale blue ppt, deep blue solution excess." }, { front: "NPK fertiliser?", back: "N,P,K nutrients." }, { front: "Le Chatelier low T favours NH₃ but?", back: "Rate slower — compromise T." }, { front: "High P favours?", back: "Fewer gas moles side — NH₃." }, { front: "Natural ammonia source?", back: "Decomposition, bacterial." }, { front: "Ammonium nitrate explosive risk?", back: "Oxidiser — careful storage." }, { front: "Nitrate leaching?", back: "Eutrophication risk." }, { front: "Haber energy intensive?", back: "Fossil H₂ often." }, { front: "NH₃ bp vs H₂O?", back: "Lower — H-bond weaker than water." }],
    quiz: [
      Q("NH₃ turns damp red litmus:", "Red", "Blue", "No change", "Green", 1, "Base."),
      Q("Haber nitrogen source:", "Air fractionation", "Only NH₄Cl", "Urea burn", "Water only", 0, "N₂ from air."),
      Q("Forward reaction to NH₃ is:", "Endothermic", "Exothermic", "Zero ΔH", "Only physical", 1, "Heat released."),
      Q("Higher pressure in Haber:", "Less NH₃", "More NH₃ equilibrium", "No effect", "Explodes always", 1, "Fewer gas moles."),
      Q("NH₄Cl + NaOH warmed:", "Cl₂", "NH₃", "H₂", "N₂", 1, "Ammonium test."),
      Q("NH₃ in water equation simplified:", "NH₃+H₂O⇌NH₄⁺+OH⁻", "Only NH₄OH molecule", "No ions", "Only H⁺", 0, "Equilibrium."),
      Q("Fertiliser from NH₃ not:", "Urea", "Ammonium salts", "Diamond", "NH₄NO₃", 2, "Not carbon allotrope."),
      Q("Catalyst in Haber:", "Pt only", "Fe", "Ni", "Enzyme", 1, "Iron promoted."),
      Q("Nitric acid from ammonia:", "Ostwald process", "Contact only", "Haber only", "Electrolysis", 0, "Oxidation steps."),
      Q("NH₃ density vs air:", "Lighter", "Heavier", "Same", "No mass", 0, "Mr 17<29."),
      Q("Why compress gases in Haber:", "Increase rate and shift equilibrium", "Only cooling", "Remove catalyst", "Dilute", 0, "More collisions."),
      Q("Equilibrium means:", "Forward stops", "Forward=reverse rates", "Only products", "No catalyst", 1, "Dynamic."),
      Q("NH₃ hydrogen bonding:", "Yes with water", "Never", "Only ionic", "Only metal", 0, "N lone pair."),
      Q("Ammonium nitrate in soil:", "N source", "Only P", "Toxic metal", "Inert sand", 0, "N fertiliser."),
      Q("Biological nitrogen fixation:", "Lightning only", "Bacteria in legumes", "Only Haber", "Oceans only", 1, "Rhizobia."),
      Q("NH₃ toxic inhalation:", "Respiratory irritant", "Nutrient only", "Inert", "Healing", 0, "Safety."),
      Q("Dry NH₃ does not turn litmus on paper without:", "Water", "Heat only", "O₂", "Cl₂", 0, "Needs moisture."),
      Q("Reverse of Haber:", "NH₃ decomposes to N₂+H₂ at very high T", "Never", "Only liquid", "Only catalyst", 0, "Endothermic back."),
      Q("Eutrophication from excess N:", "Algal bloom", "Ozone hole", "Acid rain only", "Nothing", 0, "Nutrient runoff."),
      Q("NH₃ + HCl gas:", "White smoke NH₄Cl", "Blue solution", "No reaction", "Cl₂", 0, "Solid formation."),
      Q("Industrial H₂ for Haber often from:", "Natural gas steam reforming", "Only water split", "Air only", "Coal never", 0, "CH₄+H₂O."),
      Q("NH₃ lone pair:", "Lewis base", "Lewis acid only", "No electrons", "Only metal", 0, "Donor."),
      Q("pH of 0.1 M NH₃ ~:", "1", "7", "11", "14", 2, "Weak base ~11."),
      Q("Double salt ammonium (context):", "NH₄Fe(SO₄)₂ type", "Only NaCl", "Gas", "Diamond", 0, "Alum analogues."),
      Q("Why not extreme low T in Haber:", "Rate too slow", "Explosion", "No catalyst", "No N₂", 0, "Kinetic limit."),
      Q("NOₓ from fertiliser overuse:", "Can acidify/runoff issues", "Only ozone", "Helium release", "None", 0, "Environmental."),
    ],
    trueFalse: [TF("Haber process runs at room temperature industrially.", false, "~450°C."), TF("Ammonia is a base in Brønsted sense.", true, "Accepts H⁺."), TF("All soil nitrogen is immediately plant-available.", false, "Mineralisation needed."), TF("NH₄⁺ in solution acidic hydrolysis.", true, "Weak base conjugate."), TF("Liquid ammonia autoionises like water.", true, "2NH₃⇌NH₄⁺+NH₂⁻ minimal."), TF("Urea hydrolyses to ammonia in soil.", true, "Enzyme urease."), TF("Haber fixed N enabled population growth.", true, "Historical impact."), TF("NH₃ is stored as pressurised liquid.", true, "Liquefaction."), TF("Ammonium salts with nitrate are always safe to heat.", false, "Decomposition/explosion risk."), TF("N₂ is very inert at room T.", true, "Strong triple bond."), TF("Catalyst increases equilibrium yield.", false, "Speeds both ways equally."), TF("NH₃ is trigonal pyramidal.", true, " Lone pair on N.")],
  },
  {
    id: "10", theme: T2, title: "Qualitative Analysis",
    cheatBlocks: [{ title: "Cations", points: ["NaOH: Cu²⁺ blue ppt; Fe²⁺ green; Fe³⁺ brown; Al³⁺/Zn²⁺ white soluble in excess NaOH.", "Flame: Na yellow; K lilac (cobalt glass); Cu green-blue."] }, { title: "Anions", points: ["CO₃²⁻ + acid → CO₂ limewater milky.", "Cl⁻ + AgNO₃ → white AgCl (insoluble in dil HNO₃).", "SO₄²⁻ + Ba²⁺ → white BaSO₄."] }],
    flashcards: [{ front: "Carbonate test?", back: "Acid → CO₂, limewater." }, { front: "AgBr colour?", back: "Cream ppt." }, { front: "AgI?", back: "Yellow." }, { front: "NH₄⁺ test?", back: "NaOH heat, NH₃." }, { front: "Acidify before AgNO₃ nitrate test why?", back: "Remove CO₃²⁻ interference." }, { front: "Fe³⁺ SCN⁻ blood red?", back: "Complex (A-level)." }, { front: "Ca²⁺ flame?", back: "Brick red-orange." }, { front: "Li flame?", back: "Crimson." }, { front: "Sulfite + acid?", back: "SO₂ — reduces dichromate." }, { front: "Nitrate brown ring test?", back: "Historical wet test." }, { front: "Phosphate + ammonium molybdate?", back: "Yellow ppt (adv)." }, { front: "Starch iodine?", back: "Blue-black." }, { front: "Pb²⁺ + Cl⁻ hot?", back: "Soluble cold white ppt." }, { front: "Chromate CrO₄²⁻ colour?", back: "Yellow." }],
    quiz: [
      Q("CO₂ test:", "Relights splint", "Limewater milky", "White ppt AgNO₃", "Blue litmus", 1, "Carbonate/acid."),
      Q("Cl⁻ with AgNO₃:", "Black", "White", "Yellow", "Red", 1, "AgCl."),
      Q("AgCl in dil NH₃:", "Dissolves", "Insoluble", "Explodes", "Yellow", 0, "Complex [Ag(NH₃)₂]⁺."),
      Q("Ba²⁺ for sulfate:", "Soluble ppt", "White BaSO₄", "Gas", "Blue", 1, "Insoluble."),
      Q("Cu²⁺ + NaOH:", "Green", "Blue ppt", "Brown", "No ppt", 1, "Cu(OH)₂."),
      Q("Fe²⁺ + NaOH air:", "Stays green only", "Turns brown surface", "Dissolves", "Gas", 1, "Oxidises to Fe(III)."),
      Q("Al³⁺ + excess NaOH:", "Ppt stays", "Dissolves", "Red", "Black", 1, "Amphoteric."),
      Q("Zn²⁺ + excess NaOH:", "Insoluble", "Dissolves", "Only gas", "Blue", 1, "Zincate."),
      Q("K⁺ flame through cobalt glass:", "Yellow", "Lilac", "Green", "Red", 1, "Mask Na yellow."),
      Q("Na⁺ flame:", "Lilac", "Yellow", "Green", "Blue", 1, "Intense yellow."),
      Q("NH₄⁺ without NaOH heat:", "Always NH₃", "Need OH⁻ heat", "Only blue", "Cl₂", 1, "Liberate gas."),
      Q("Sulfate test acidify Ba²⁺:", "Avoid CO₃ ppt", "No reason", "Colour", "Speed", 0, "BaCO₃ also white."),
      Q("I⁻ + Ag⁺:", "White", "Cream", "Yellow", "Clear", 2, "AgI."),
      Q("Br⁻ + Ag⁺:", "White", "Cream", "Yellow", "Black", 1, "AgBr."),
      Q("Pb²⁺ toxic:", "Heavy metal", "Nutrient", "Noble gas", "Halogen", 0, "Poison."),
      Q("Gas turns acidified K₂Cr₂O₇ green:", "CO₂ only", "SO₂ reducing", "N₂", "O₂", 1, "Reducing gas."),
      Q("HCO₃⁻ + acid:", "Same CO₂ test as CO₃²⁻", "No gas", "Only H₂", "Cl₂", 0, "Also CO₂."),
      Q("Flame test wire clean:", "HCl dip heat", "Only water", "Oil", "Sugar", 0, "Remove contamination."),
      Q("MnO₄⁻ colour:", "Colourless", "Purple", "Yellow", "Pink only", 1, "Permanganate."),
      Q("Cu²⁺ concentrated solution colour:", "Blue", "Green/yellow high Cl⁻", "Always red", "None", 0, "Aqua complex."),
      Q("Ferricyanide test Fe²⁺ (adv):", "Turnbull's blue", "Only gas", "White", "Silver", 0, "Qual scheme."),
      Q("Nitrate reduction to NH₃ Devarda (context):", "Alloy reduces", "Only heat", "Only acid", "Light", 0, "Old test."),
      Q("Silver mirror Tollen aldehyde:", "Not cation test", "Organic", "Cl⁻", "SO₄²⁻", 1, "Different test."),
      Q("Gas relights glowing splint:", "CO₂", "O₂", "N₂", "Cl₂", 1, "Oxygen test."),
      Q("Pop test gas:", "O₂", "H₂", "CO₂", "NH₃", 1, "Hydrogen."),
      Q("Pb²⁺ + I⁻:", "White", "Yellow ppt", "Gas", "Blue", 1, "PbI₂."),
    ],
    trueFalse: [TF("AgBr is more soluble than AgCl in water.", true, "Ksp larger."), TF("All metal hydroxides dissolve in excess NaOH.", false, "Only amphoteric."), TF("Flame test is definitive for anion.", false, "Cation."), TF("Dilute HNO₃ used with AgNO₃ to prevent unwanted ppt.", true, "Carbonate removal."), TF("BaSO₄ dissolves in dilute HCl.", false, "Insoluble."), TF("NH₃ from ammonium salt confirms NH₄⁺.", true, "Gas tests."), TF("Fe³⁺ and Fe²⁺ both give same colour NaOH initially.", false, "Green vs brownish."), TF("Copper carbonate green solid adds acid → CO₂.", true, "Carbonate."), TF("Silver nitrate stains skin brown.", true, "Photodecomposition."), TF("Sodium flame can mask potassium without cobalt glass.", true, "Yellow overlap."), TF("Chromate-dichromate pH equilibrium.", true, "Orange/yellow."), TF("Qualitative means identity not amount.", true, "vs quantitative.")],
  },
  {
    id: "11", theme: T2, title: "Redox Chemistry",
    cheatBlocks: [{ title: "Definitions", points: ["OIL RIG — oxidation is loss of electrons.", "Oxidising agent is reduced; reducing agent oxidised.", "Gain O / loss H often oxidation (inorganic shortcuts)."] }, { title: "Examples", points: ["Halogen displacement: more reactive halogen displaces lower.", "Metal displacement: higher in series displaces lower ions."] }],
    flashcards: [{ front: "Oxidising agent?", back: "Gains electrons (reduced)." }, { front: "Cl₂ + Br⁻?", back: "Br₂ + Cl⁻." }, { front: "Combustion Mg?", back: "Mg oxidised, O₂ reduced." }, { front: "Acidified MnO₄⁻ colour change?", back: "Purple → colourless (Mn²⁺)." }, { front: "Cr₂O₇²⁻ reduced?", back: "Orange → green Cr³⁺." }, { front: "Half-equation balance?", back: "Atoms then charge with e⁻." }, { front: "Disproportionation?", back: "Same element oxidised and reduced." }, { front: "Fuel cell?", back: "Redox produces electrical energy." }, { front: "Corrosion iron?", back: "Oxidation Fe → rust." }, { front: "Sacrificial Zn?", back: "Zn oxidises instead of Fe." }, { front: "Bleach oxidises?", back: "ClO⁻ oxidising." }, { front: "Photosynthesis redox?", back: "CO₂ reduced, H₂O oxidised." }, { front: "Highest oxidation state Mn in MnO₄⁻?", back: "+7." }, { front: "Gain electrons is?", back: "Reduction." }],
    quiz: [
      Q("In Zn + Cu²⁺ → Zn²⁺ + Cu, oxidising agent:", "Zn", "Cu²⁺", "Zn²⁺", "Cu", 1, "Cu²⁺ reduced."),
      Q("Oxidation is:", "Gain e⁻", "Loss e⁻", "Gain H", "Loss O", 1, "OIL."),
      Q("Cl₂ + 2I⁻ → 2Cl⁻ + I₂: oxidised:", "Cl⁻", "I⁻", "Cl₂", "I₂", 1, "I⁻ to I₂."),
      Q("Which is reduced in Fe₂O₃ + 3CO → 2Fe + 3CO₂:", "Fe in oxide", "C in CO", "O only", "None", 0, "Fe +3→0."),
      Q("Reducing agent in same:", "Fe₂O₃", "CO", "CO₂", "Fe", 1, "CO oxidised to CO₂."),
      Q("Half-equation Fe²⁺ → Fe³⁺:", "+ e⁻", "- e⁻", "+2H⁺", "No change", 1, "Loses electron."),
      Q("Acidified MnO₄⁻ + Fe²⁺:", "Fe oxidised", "Fe reduced only", "No reaction", "Only Mn oxidised", 0, "Fe²⁺→Fe³⁺."),
      Q("More reactive halogen displaces:", "Higher halide from solution", "Lower halogen from its halide", "Water", "Noble gases", 1, "Cl₂ + Br⁻."),
      Q("Oxidation state O in H₂O₂:", "-2", "-1", "0", "+1", 1, "Peroxide."),
      Q("O in OF₂:", "-2", "+2", "-1", "0", 1, "F more EN."),
      Q("Disproportionation Cl₂ + OH⁻ cold:", "Cl⁻ + ClO⁻", "Only Cl⁻", "Only ClO₃⁻", "O₂", 0, "Cold dilute."),
      Q("N in NH₃:", "-3", "+3", "+5", "0", 0, "H +1."),
      Q("S in SO₄²⁻:", "+4", "+6", "-2", "0", 1, "Oxide sum."),
      Q("Balanced e⁻ in Cu + Ag⁺:", "Cu → Cu²⁺ +2e; Ag⁺ +e → Ag", "1e each", "No e⁻", "3e", 0, "Stoichiometry 1Cu:2Ag."),
      Q("Internal combustion NOₓ:", "N₂ oxidised", "N₂ + O₂ high T", "Only fuel", "H₂O", 1, "Fixation."),
      Q("Antioxidant vitamin C:", "Reducing agent", "Oxidising", "Catalyst", "Inert", 0, "Reduces radicals."),
      Q("Electrolysis cathode is:", "Oxidation", "Reduction", "Both", "Neither", 1, "Reduction."),
      Q("Galvanic cell anode:", "Oxidation", "Reduction", "No electron flow", "Both", 0, "Electron source."),
      Q("Rust Fe oxidation state final hydrous oxide:", "0", "+2", "+3", "-3", 2, "Fe(III) oxide hydroxide."),
      Q("H₂S reduces acidified dichromate:", "S oxidised", "Cr oxidised", "No redox", "Only physical", 0, "S²⁻ → S."),
      Q("KMnO₄ is:", "Reducing agent", "Oxidising agent", "Catalyst only", "Acid", 1, "Strong oxidant."),
      Q("Same element oxidation states in O₂:", "0", "-2", "+2", "-1", 0, "Elemental."),
      Q("Combustion hydrocarbon C oxidised to:", "Always only CO", "CO₂ if complete", "Only C", "H₂", 1, "Complete."),
      Q("Nitrate in acid with Cu:", "H₂", "NOₓ gases", "N₂ only", "Cl₂", 1, "Oxidising acid."),
      Q("Balancing redox acidic MnO₄⁻ + C₂O₄²⁻:", "Electrons + H₂O + H⁺", "Only heat", "No H⁺", "Only OH⁻", 0, "Acid medium."),
      Q("Superoxide KO₂ (adv) O avg:", "-½", "-2", "-1", "0", 0, "Interesting."),
    ],
    trueFalse: [TF("If a species gains electrons it is oxidised.", false, "Reduced."), TF("All combustion reactions are redox.", true, "O₂ involved."), TF("Single displacement reactions are often redox.", true, "Electron transfer."), TF("In a redox reaction total oxidation states change sum to zero net element.", true, "Conservation."), TF("H₂ can act as reducing agent.", true, "Fuels."), TF("Concentrated H₂SO₄ oxidises Cu.", false, "Needs nitric or hot conc sulfuric specific cases."), TF("The species with highest oxidation state always oxidises others.", false, "Kinetics matter."), TF("Oxidation and reduction always occur together.", true, "Redox pair."), TF("Cl₂ is stronger oxidant than I₂.", true, "Reactivity series halogens."), TF("Zn protects Fe by preferential oxidation.", true, "Sacrificial."), TF("Photosynthesis overall reduces CO₂.", true, "To carbohydrate."), TF("Respiration oxidises glucose.", true, "To CO₂.")],
  },
  {
    id: "12", theme: T2, title: "Electrochemistry",
    cheatBlocks: [{ title: "Electrolysis", points: ["Cathode − reduction; anode + oxidation.", "Molten ionic: metal at cathode, non-metal anode.", "Aqueous: H₂ or O₂ may form depending on reactivity/concentration."] }, { title: "Cells", points: ["Voltaic: spontaneous; more reactive metal negative electrode.", "Electroplating: object at cathode."] }],
    infographics: [{ svg: svgEl, caption: "Electrolysis cell (schematic)" }],
    flashcards: [{ front: "Cathode attracts?", back: "Cations." }, { front: "Anode molten NaCl?", back: "Cl₂." }, { front: "Cu²⁺ aq inert electrodes?", back: "Cu plates cathode." }, { front: "Electrolyte?", back: "Ions conduct." }, { front: "Faraday (qual)?", back: "More charge ∝ more substance." }, { front: "Mg–Cu cell negative?", back: "Mg." }, { front: "Salt bridge?", back: "Completes ion circuit." }, { front: "Standard electrode potential?", back: "Measure vs reference." }, { front: "Al extraction?", back: "Electrolysis molten cryolite Al₂O₃." }, { front: "Brine electrolysis diaphragm?", back: "NaOH + Cl₂ + H₂." }, { front: "Anode in cell is oxidation?", back: "Yes in voltaic cell." }, { front: "Overpotential?", back: "Extra voltage needed (kinetics)." }, { front: "Inert electrode Pt?", back: "Unreactive." }, { front: "Ion migration cathode?", back: "Positive ions reduced." }],
    quiz: [
      Q("Cathode in electrolysis:", "Positive", "Negative", "No charge", "AC", 1, "Cations go there."),
      Q("Molten PbBr₂ anode:", "Pb", "Br₂", "H₂", "O₂", 1, "Halide oxidised."),
      Q("Electroplate object:", "Anode", "Cathode", "Either", "Outside cell", 1, "Metal deposits."),
      Q("Electrolysis needs:", "Spontaneous", "Electrical energy input", "Light only", "Heat only", 1, "Non-spontaneous driven."),
      Q("Dilute H₂SO₄ electrolysis inert:", "Na at cathode", "H₂ and O₂", "Only SO₂", "Cu", 1, "Water electrolysis dominant."),
      Q("CuSO₄ aq Cu electrodes:", "Cu dissolves anode plates cathode", "Only H₂", "No change", "Cl₂", 0, "Refining."),
      Q("More reactive metal as cell anode:", "Oxidised", "Reduced", "Inert", "Coated", 0, "Loses e⁻."),
      Q("E° cell >0 means:", "Non-spontaneous", "Spontaneous as written", "Equilibrium", "No electrons", 1, "ΔG<0."),
      Q("Ion flow salt bridge to cathode compartment:", "Anions", "Cations", "Electrons", "None", 0, "Balance charge."),
      Q("Al extraction method:", "Coke reduction", "Electrolysis molten", "Displacement", "Acid leach only", 1, "Too reactive."),
      Q("Na extraction:", "H₂ reduction", "Electrolysis molten NaCl", "Carbon only", "Titanium catalyst", 1, "Reactive metal."),
      Q("Charge on anion moves to anode in electrolysis:", "True migration", "False", "Only metals", "Gas only", 0, "Anions to positive."),
      Q("Brine products at electrodes:", "Na metal always", "Cl₂ H₂ NaOH", "Only O₂", "N₂", 1, "Industrial chlor-alkali."),
      Q("Why cryolite in Al extraction:", "Lowers melting point", "Increases mp", "Colour", "Catalyst only", 0, "Solvent for alumina."),
      Q("Fuel cell vehicle advantage:", "Only water from H₂/O₂ ideal", "No energy input ever", "Solid only", "No storage issue", 0, "Clean product."),
      Q("Corrosion iron needs:", "O₂ and H₂O often", "Only N₂", "Only dry air", "Vacuum", 0, "Electrochemical rust."),
      Q("Sacrificial anode connected to ship:", "Cathode protected", "More reactive metal corrodes", "No effect", "Insulator", 1, "Zn/Mg blocks."),
      Q("Electrolysis of acidified water O₂ at:", "Cathode", "Anode", "Both", "Neither", 1, "OH⁻/H₂O oxidised."),
      Q("Silver plating electrolyte:", "Ag⁺ solution", "Only NaCl", "Only sugar", "Oil", 0, "Ag source."),
      Q("Charge carriers in metal wire:", "Ions", "Electrons", "Protons", "Neutrons", 1, "e⁻ flow."),
      Q("Daniel cell Zn in ZnSO₄:", "Positive electrode", "Negative electrode", "Salt", "Membrane", 1, "Zn oxidises."),
      Q("During charging lead-acid battery:", "Electrolysis reversing cell", "Only discharge", "No redox", "Fusion", 0, "Non-spontaneous charge."),
      Q("Why AC not used simple electrolysis cell:", "No net product", "Better yield", "Safer always", "Required", 0, "Alternating redox."),
      Q("Concentrated NaCl brine anode:", "O₂ preferred", "Cl₂ preferred", "H₂", "Na", 1, "High [Cl⁻]."),
      Q("Reduction at cathode always involves:", "Gain of electrons", "Loss of electrons", "Proton emission", "Neutron capture", 0, "Definition."),
      Q("Nernst idea (qual):", "Concentration affects E", "No effect", "Only gas colour", "Only solid", 0, "Le Chatelier on potentials."),
    ],
    trueFalse: [TF("In electrolysis the cathode is where oxidation happens.", false, "Reduction at cathode."), TF("Molten oxides of very reactive metals are electrolysed to extract metal.", true, "Al, Na, etc."), TF("Pure water electrolyses easily without ions.", false, "Very low conductivity."), TF("In a voltaic cell electrons flow external circuit anode to cathode.", true, "Conventional current opposite."), TF("Copper can be purified by electrolysis with impure Cu anode.", true, "Electrorefining."), TF("Hydrogen fuel cell produces electricity from H₂ and O₂.", true, "Redox cell."), TF("Electrolysis always produces elements at both electrodes.", false, "Could be water ions products."), TF("Anode in electrolysis is positive terminal of supply.", true, "Attracts anions."), TF("Faraday's laws link mass to charge.", true, "m ∝ Q."), TF("Sea water accelerates steel corrosion.", true, "Electrolyte."), TF("Gold plating uses Au³⁺ reduction at cathode.", true, "Thin layer."), TF("Mercury cell for brine is environmentally phased.", true, "Mercury pollution.")],
  },
  {
    id: "13", theme: T2, title: "Patterns in the Periodic Table",
    cheatBlocks: [{ title: "Trends", points: ["Across period: atomic radius ↓; metallic character ↓; IE ↑.", "Down group: radius ↑; metallic ↑ (Gp1); halogen reactivity ↓.", "Noble gases full outer shell — unreactive."] }, { title: "Groups", points: ["Gp1 alkali — +1 ions; violent with water down group.", "Gp17 halogens — diatomic; displacement reactivity.", "Gp18 noble gases — monatomic gases."] }],
    flashcards: [{ front: "Gp1 reactivity down?", back: "Increases." }, { front: "Halogen reactivity down?", back: "Decreases." }, { front: "Atomic radius across Period 3?", back: "Decreases." }, { front: "First IE across period?", back: "Generally increases." }, { front: "Why Fr most reactive alkali?", back: "Electron lost easily — far from nucleus." }, { front: "Electronegativity trend?", back: "↑ across, ↓ down (F max)." }, { front: "Diagonal Li~Mg similarity?", back: "Polarising power." }, { front: "Transition metals?", back: "Variable oxidation states, coloured compounds." }, { front: "Shielding effect?", back: "Inner electrons reduce nuclear pull on valence." }, { front: "Noble gas boiling point trend?", back: "Increases down (London forces)." }, { front: "Metallic bonding strength Period 3?", back: "Generally peaks middle." }, { front: "Chlorine state 25°C?", back: "Gas." }, { front: "Bromine state?", back: "Liquid." }, { front: "Iodine state?", back: "Solid." }],
    quiz: [
      Q("Most metallic Period 3:", "Cl", "Si", "Na", "S", 2, "Left."),
      Q("Smallest atom Period 2:", "Li", "Ne", "Be", "B", 1, "Right end noble small."),
      Q("Highest first IE Period 3 excluding noble:", "Na", "Mg", "Si", "Cl", 3, "Right before Ar."),
      Q("Gp17 element liquid at room T:", "F₂", "Cl₂", "Br₂", "I₂", 2, "Bromine."),
      Q("Cl₂ + KBr:", "No reaction", "Br₂ forms", "KCl only", "I₂", 1, "Displacement."),
      Q("Noble gas in lamps often:", "Ne", "Ar", "He", "Rn", 1, "Inert cheap."),
      Q("Element 2,8,8,1:", "Gp1", "Gp7", "Gp18", "Gp2", 0, "One valence e."),
      Q("Across period valence electrons Gp1→2:", "Decrease", "Increase to 3 then complex", "Constant", "Zero", 1, "Up to 3 for Na Mg Al."),
      Q("Why Al less metallic than Na same period:", "More protons hold e⁻ tighter", "Fewer protons", "Same shielding exactly", "Larger radius", 0, "Effective nuclear charge."),
      Q("Down gp1 density trend:", "Always decreases", "Generally increases then K anomaly", "Constant", "Only gas", 1, "K less dense than Na."),
      Q("Electron affinity most exothermic halogen:", "I", "Br", "Cl", "F", 2, "F small size — Cl often max in group."), 
      Q("Atomic radius Na vs Cl:", "Na smaller", "Cl smaller", "Same", "Cannot", 1, "Same period: more nuclear charge → Cl smaller."),
      Q("Melting trend alkali metals down:", "Generally decreases", "Increases", "Constant", "Only Li melts", 0, "Metallic bonding weakens."),
      Q("Which is not halogen:", "At", "Se", "I", "Br", 1, "Selenium is chalcogen."),
      Q("Oxidation state group 2:", "+1", "+2", "+3", "0", 1, "Lose 2e."),
      Q("Transition element property:", "Fixed +1 only", "Variable oxidation state", "No colour", "Gas at RT", 1, "d-block."),
      Q("Lanthanide contraction effect:", "6d and 5d similar size", "No effect", "Only s-block", "Halogens shrink", 0, "5d vs 4d."),
      Q("Hydrogen placement debate:", "Only metal", "Non-metal mostly", "Halogen always", "Noble gas", 1, "Unique."),
      Q("Silicon semiconductor:", "Metallic", "Metalloid", "Halogen", "Alkali", 1, "Period 3 metalloid."),
      Q("Fr predicted properties:", "Least volatile alkali", "Most reactive alkali", "Halogen", "Noble", 1, "Radioactive alkali."),
      Q("Ionisation energy Mg vs Al anomaly:", "Al lower (3p easier e⁻)", "Mg lower", "Same", "Both zero", 0, "s² full subshell stable Mg."),
      Q("S₂ molecule (adv):", "Like O₂ paramagnetic idea", "Single bonded only", "Noble", "Ionic", 0, "Disulfur."),
      Q("Allotropes oxygen:", "O₂ O₃", "Only O", "Fe O", "Cl O", 0, "Ozone."),
      Q("Halogen colour intensity down:", "Lighter", "Darker", "Colourless all", "Only solid colours", 1, "Deeper colour."),
      Q("Noble gas compound first (history):", "Xe compounds", "He compounds easy", "Ne many", "Ar acids", 0, "XePtF₆."),
      Q("Effective nuclear charge trend across:", "Decreases", "Increases", "Constant", "Random", 1, "Zeff up."),
    ],
    trueFalse: [TF("Fluorine is the most electronegative element.", true, "Pauling scale."), TF("Atomic radius increases down a group.", true, "Extra shell."), TF("Noble gases have zero electron affinity.", false, "Can be slightly positive/endothermic."), TF("Sodium reacts more violently with water than lithium.", true, "More reactive down gp1."), TF("All period 3 elements are metals.", false, "Si P S Cl Ar non/metalloid."), TF("Ionisation energy removes electron from gaseous atom.", true, "Definition."), TF("Halogens exist as monatomic gases.", false, "X₂ diatomic."), TF("Electronegativity of Cs is higher than F.", false, "F max."), TF("Transition metals form coloured ions often.", true, "d-d transitions."), TF("Metallic character decreases across a period.", true, "Toward non-metals."), TF("He has highest first IE.", true, "Small, tight hold."), TF("Group 1 hydroxides become more soluble down group.", true, "General trend.")],
  },
  {
    id: "14", theme: T2, title: "Reactivity Series of Metals",
    cheatBlocks: [{ title: "Series", points: ["K Na Ca Mg Al (C) Zn Fe Pb (H) Cu Ag Au — learn pattern.", "Metal above displaces ions of metal below from aqueous solution.", "Above H: H₂ from dilute acids (with caveats for passivation)."] }, { title: "Uses", points: ["Extraction: C reduces ZnO etc.; very reactive → electrolysis.", "Sacrificial protection; thermite (Al + Fe₂O₃)."] }],
    flashcards: [{ front: "Fe + CuSO₄?", back: "FeSO₄ + Cu." }, { front: "Cu + ZnSO₄?", back: "No reaction." }, { front: "K with water?", back: "Violent H₂ + strong alkali." }, { front: "Carbon reduces?", back: "Oxides of Zn and below in blast furnace context." }, { front: "Gold occurrence?", back: "Native (unreacted)." }, { front: "Iron rust?", back: "Hydrated Fe(III) oxide." }, { front: "Galvanising?", back: "Zn coat on steel." }, { front: "Stainless steel?", back: "Cr/Ni alloy corrosion resistant." }, { front: "Sn + Fe²⁺?", back: "Sn less reactive than Fe? Sn below Fe — no displacement of Fe²⁺ by Sn... Sn above Fe? Actually Sn above Fe in some tables — check: Fe more reactive than Sn in many UK series — Fe above Sn. So Sn cannot displace Fe²⁺. Fe displaces Sn²⁺." }, { front: "Hydrogen reference?", back: "Metals above H displace H₂ from dilute acid." }, { front: "Thermite use?", back: "Weld rails; molten Fe." }, { front: "Blast furnace reducing agent?", back: "C/CO." }, { front: "Native copper?", back: "Sometimes found uncombined." }, { front: "Silver tarnish?", back: "Ag₂S from H₂S." }],
    quiz: [
      Q("Displaces Cu from CuSO₄:", "Ag", "Zn", "Au", "Pt", 1, "Zn above Cu."),
      Q("No reaction with cold water:", "Na", "K", "Ca", "Mg", 3, "Mg very slow cold."),
      Q("Most reactive listed:", "Au", "K", "Cu", "Ag", 1, "Top of series."),
      Q("H₂ from dilute HCl:", "Cu", "Fe", "Ag", "Au", 1, "Fe above H."),
      Q("Thermite Al + Fe₂O₃:", "Al oxidised", "Fe oxidised", "O₂ product", "No heat", 0, "Al reduces Fe."),
      Q("Carbon cannot reduce at high T:", "ZnO", "Al₂O₃", "Fe₂O₃", "PbO", 1, "Al too reactive — electrolysis."),
      Q("Sacrificial anode for iron ship:", "Cu", "Zn", "Ag", "Sn", 1, "Zn more reactive."),
      Q("Native metal likely:", "Na", "Au", "Mg", "Al", 1, "Unreactive."),
      Q("Fe + Sn²⁺:", "Fe²⁺ + Sn", "No reaction", "Fe³⁺ only", "Sn + Fe", 0, "Fe above Sn displaces."),
      Q("Cu + AgNO₃:", "No reaction", "Cu²⁺ + Ag", "Cu + Ag only solid", "Gas", 1, "Cu above Ag."),
      Q("Metal oxide most easily reduced by H₂:", "Na₂O", "CuO", "Al₂O₃", "MgO", 1, "Lower in series easier reduce."),
      Q("Blast furnace iron ore reduced by:", "Only H₂", "CO/C", "Al", "Electrons only", 1, "Reductants."),
      Q("Why Al resists corrosion:", "Oxide layer", "No oxide", "Liquid", "Gold coat", 0, "Al₂O₃ passive."),
      Q("Mg + steam:", "No reaction", "MgO + H₂", "MgH₂ only", "Explodes always", 1, "Hot."),
      Q("Pb + HCl dilute:", "Fast H₂", "Slow/no simple H₂", "Cl₂", "PbCl₂ insoluble coats", 3, "Insoluble chloride layer."),
      Q("Silver in HNO₃ conc:", "No reaction", "Dissolves (redox)", "Only H₂", "Heats only", 1, "Oxidising acid."),
      Q("Order Zn Fe Cu reactivity:", "Zn>Fe>Cu", "Cu>Fe>Zn", "Fe>Zn>Cu", "Same", 0, "Series."),
      Q("Hydrogen in series is reference for:", "Halogen displacement", "Acid-metal", "Precipitation", "Titration", 1, "H₂ liberation."),
      Q("Rusting needs:", "Dry O₂ only", "O₂ + H₂O", "Only N₂", "Only salt never", 1, "Electrochemical."),
      Q("Zinc-coated steel scratched:", "Zn still protects Fe cathodically", "Fe rusts immediately fast", "Cu needed", "No effect", 0, "Sacrificial."),
      Q("Metal extracted by electrolysis molten:", "Fe", "Al", "Cu", "Pb", 1, "Very reactive."),
      Q("Carbon reduces PbO on heating:", "Yes often", "Never", "Only liquid", "Only with Pt", 0, "Below Al in series."),
      Q("Gold jewellery alloy:", "Pure always", "Cu added hardness", "Na added", "Cl added", 1, "Hardness."),
      Q("Fe + acid → Fe²⁺ or Fe³⁺ dilute:", "Fe²⁺ typically", "Fe³⁺ always", "Fe⁰", "No ions", 0, "Dilute HCl."),
      Q("Metal + water steam general gp1:", "Hydroxide + H₂", "Only oxide", "No reaction", "Only O₂", 0, "Alkali metals."),
      Q("Reactivity series from reduction potentials (concept):", "More negative E° more reactive metal", "More positive more reactive", "No link", "Only non-metals", 0, "Trend."),
    ],
    trueFalse: [TF("Copper reacts with dilute hydrochloric acid to give hydrogen.", false, "Below hydrogen."), TF("Iron is more reactive than carbon in extracting aluminium.", false, "Al more reactive — C cannot reduce Al₂O₃ commercially."), TF("Zinc will displace lead from lead nitrate solution.", true, "Zn above Pb."), TF("Gold is found native because it is unreactive.", true, "Low reactivity."), TF("Magnesium burns in CO₂ (spark).", true, "Reduces CO₂."), TF("All metals conduct electricity.", true, "Metallic bonding."), TF("Stainless steel never rusts.", false, "Can under harsh conditions."), TF("Alkali metals stored under oil.", true, "Prevent water contact."), TF("Silver is a good conductor of electricity.", true, "Used in contacts."), TF("Iron is below hydrogen in reactivity series.", false, "Above — Fe + acid → H₂."), TF("Carbon can reduce iron(III) oxide in blast furnace.", true, "CO/C reduction."), TF("Mercury liquid metal below hydrogen.", false, "Hg below H — no H₂ from dilute acid.")],
    orderGame: ["K", "Na", "Ca", "Mg", "Al", "Zn", "Fe", "Pb", "H", "Cu", "Ag"],
    orderTitle: "Metals (simplified series)",
  },
  {
    id: "15", theme: T2, title: "Chemical Energetics",
    cheatBlocks: [{ title: "Enthalpy", points: ["Exothermic: ΔH negative — heat out.", "Endothermic: ΔH positive — heat in.", "Activation energy Ea — hill on profile."] }, { title: "Bonds", points: ["Breaking bonds endothermic; making bonds exothermic.", "ΔH reaction ≈ bonds broken − made (bond energy estimate)."] }, { title: "Catalyst", points: ["Lowers Ea; does not change ΔH.", "Speeds forward and reverse equally."] }],
    flashcards: [{ front: "Combustion ΔH?", back: "Negative (exothermic)." }, { front: "Photosynthesis overall?", back: "Endothermic." }, { front: "Neutralisation?", back: "Exothermic." }, { front: "Thermal decomposition CaCO₃?", back: "Endothermic." }, { front: "Bond breaking?", back: "Endothermic." }, { front: "Haber forward exothermic?", back: "Yes — low T favours NH₃ but rate trade-off." }, { front: "ΔH solution NH₄NO₃ in water?", back: "Endothermic cold pack." }, { front: "Activation energy with catalyst?", back: "Lower pathway." }, { front: "Enthalpy level diagram exo?", back: "Products lower than reactants." }, { front: "Standard conditions?", back: "298 K, 100 kPa, stated state." }, { front: "Hess's law?", back: "Path independent — cycle sums." }, { front: "Formation enthalpy?", back: "Elements → 1 mol compound." }, { front: "Combustion enthalpy?", back: "Substance + O₂ → oxides." }, { front: "Lattice enthalpy?", back: "Ions → ionic solid (gaseous ions)." }],
    quiz: [
      Q("Exothermic:", "Products higher energy", "Products lower energy than reactants", "No energy change", "Only light in", 1, "Heat released."),
      Q("Endothermic decomposition CaCO₃:", "Releases heat", "Absorbs heat", "No ΔH", "Only physical", 1, "Needs strong heating."),
      Q("Catalyst effect on ΔH:", "Increases", "Decreases", "No change", "Doubles", 2, "Only Ea."),
      Q("Bond forming:", "Endothermic", "Exothermic", "Zero", "Only gas", 1, "Stability."),
      Q("Overall exothermic if:", "Bonds broken > formed energy", "Bonds formed release more than break cost", "Only catalyst", "No bonds", 1, "Net downhill."),
      Q("Hand warmer iron oxidation:", "Endothermic", "Exothermic", "No reaction", "Nuclear", 1, "Heat pack."),
      Q("Cold pack NH₄NO₃:", "Exothermic dissolving", "Endothermic dissolving", "No ΔH", "Only gas", 1, "Absorbs heat."),
      Q("Ea is:", "Total ΔH", "Barrier to reaction", "Only product energy", "Catalyst mass", 1, "Activation."),
      Q("Reverse reaction ΔH:", "Same as forward", "Opposite sign", "Always zero", "Twice forward", 1, "Hess."),
      Q("Combustion methane sign:", "Positive ΔH", "Negative ΔH", "Zero", "Undefined", 1, "Exothermic."),
      Q("Neutralisation strong acid-base:", "Strongly endothermic", "Exothermic ~57 kJ/mol per mol water context", "No heat", "Only gas", 1, "Typical."),
      Q("Graph exothermic profile:", "Peak below products", "Products below reactants energy", "Flat", "No peak", 1, "Downhill net."),
      Q("Enzyme:", "Raises ΔH", "Lowers Ea", "Changes equilibrium only", "Consumes product", 1, "Biocatalyst."),
      Q("Fuel higher enthalpy density:", "More energy per kg", "Less energy", "No combustion", "Only solid", 0, "Useful fuel."),
      Q("Hess cycle for enthalpy formation:", "Path dependent", "Sum around cycle zero", "Only gases", "No numbers", 1, "Conservation."),
      Q("Bond energy O=O high means:", "Hard to break", "Easy to break", "No O₂", "Liquid only", 0, "Strong bond."),
      Q("Explosion highly exothermic fast:", "Slow release", "Rapid exothermic gas expansion", "Endothermic", "Only light", 1, "TNT etc."),
      Q("Photosynthesis light energy:", "Stored in products endothermic overall", "Released fully", "No storage", "Only heat out", 0, "ΔH>0 overall."),
      Q("Respiration glucose:", "Exothermic", "Endothermic", "No redox", "Only physical", 0, "Energy release."),
      Q("Dissolving NaOH in water:", "Cold", "Heats up", "No change", "Freezes", 1, "Exothermic solvation."),
      Q("Sublimation iodine ΔH:", "Negative always", "Positive", "Zero", "Only liquid", 1, "Endothermic."),
      Q("Activation energy without catalyst higher:", "Slower reaction", "Faster", "Same rate always", "No reaction ever", 0, "Fewer successful collisions."),
      Q("ΔHf° element standard state:", "Zero", "Always positive", "Always negative", "100 kJ", 0, "Reference."),
      Q("Combustion incomplete CO vs CO₂:", "CO releases more heat per C", "CO₂ releases more complete combustion", "Same", "Neither exothermic", 1, "Complete more exothermic per C."),
      Q("Le Chatelier exothermic forward reaction low T:", "Favours products equilibrium", "Favours reactants", "No effect", "Explodes", 0, "Heat as product."),
      Q("Calorimetry heat capacity (concept):", "q = mcΔT", "Only volume", "Only pressure", "No formula", 0, "Specific heat."),
    ],
    trueFalse: [TF("All spontaneous reactions are exothermic.", false, "Entropy can drive endothermic."), TF("Catalyst increases equilibrium yield of exothermic forward.", false, "Speed only."), TF("Breaking all bonds in methane is endothermic.", true, "Need energy input."), TF("Formation of water from H₂ and O₂ is highly exothermic.", true, "Explosive mix."), TF("ΔH depends on state of reactants (s,l,g,aq).", true, "State matters."), TF("Activation energy can be supplied by heat or light.", true, "Initiation."), TF("Bond energy is always positive magnitude for breaking.", true, "Endothermic process."), TF("An endothermic reaction feels cold to touch on flask.", true, "Absorbs heat from surroundings."), TF("N₂ + O₂ → NO is endothermic.", true, "Lightning fixation."), TF("Dissolving NH₄Cl is endothermic.", true, "Cold flask."), TF("Hess's law is consequence of enthalpy state function.", true, "Path independent."), TF("Lattice enthalpy MgO very exothermic.", true, "Strong ionic attraction.")],
  },
  {
    id: "16", theme: T2, title: "Rate of Reactions",
    cheatBlocks: [{ title: "Factors", points: ["Concentration ↑ → collision frequency ↑.", "Temperature ↑ → more particles ≥ Ea; more frequent collisions.", "Surface area ↑ (solid) → more exposed sites.", "Catalyst: lower Ea."] }, { title: "Measurement", points: ["Gas volume vs time; mass loss; colour change; titrate samples quenched.", "Initial rate = gradient at t=0."] }, { title: "Collision theory", points: ["Particles must collide with correct orientation and ≥ Ea for reaction."] }],
    flashcards: [{ front: "Rate units?", back: "mol dm⁻³ s⁻¹ or g s⁻¹ etc." }, { front: "Catalyst?", back: "Same at end; alternative pathway." }, { front: "Powder vs lump zinc acid?", back: "Powder faster — area." }, { front: "Maxwell-Boltzmann T↑?", back: "More molecules past Ea." }, { front: "Effective collision?", back: "Sufficient energy + orientation." }, { front: "Inhibitor?", back: "Slows catalyst poison." }, { front: "Clock reaction?", back: "Sudden colour after delay." }, { front: "Half-life first order?", back: "Constant." }, { front: "Concentration doubles rate doubles first order?", back: "Yes linear." }, { front: "Enzyme denatured high T?", back: "Loses shape — rate drops." }, { front: "Pressure gas reaction rate?", back: "Higher P often faster (more conc)." }, { front: "Stirring?", back: "Mixes — increases effective collisions surface." }, { front: "Quenching sample?", back: "Stops reaction for titration." }, { front: "Photochemical initiation?", back: "Light provides activation." }],
    quiz: [
      Q("Increase rate CaCO₃ + HCl:", "Use large lumps", "Heat and powder", "Dilute more", "Remove acid", 1, "T and surface area."),
      Q("Lower concentration usually:", "Faster", "Slower", "Same", "Explosive", 1, "Fewer collisions."),
      Q("Catalyst:", "Consumed net", "Lowers Ea", "Changes ΔH lots", "Shifts equilibrium only", 1, "Pathway."),
      Q("Flat on volume-time curve:", "Fastest rate", "Reaction complete or very slow", "Explosion", "Catalyst added mid", 1, "Level off."),
      Q("Temperature 10°C rise often:", "Halves rate", "Doubles rate approx rule of thumb", "No change", "Stops", 1, "Rough guide."),
      Q("MnO₂ in H₂O₂:", "Reactant", "Catalyst", "Product", "Inhibitor", 1, "Speeds decomposition."),
      Q("Gas pressure on 2NO+O₂:", "No effect", "Higher P faster", "Only solid", "Only liquid", 1, "More gas molecules per volume."),
      Q("Measuring rate via mass loss:", "CO₂ escape in carbonate+acid", "Only gain", "Never", "Only metal", 0, "Open system."),
      Q("Initial rate from graph:", "Tangent at t=0", "Final height", "Average whole", "Zero always", 0, "Steepest start."),
      Q("Heterogeneous catalyst:", "Same phase as reactants", "Different phase often surface", "Only enzyme", "Only gas", 1, "Surface catalysis."),
      Q("Homogeneous catalyst:", "Same phase", "Solid only", "Only liquid metal", "Never used", 0, "Fe³⁺ in solution."),
      Q("Autocatalysis MnO₄⁻ oxalic:", "Product speeds", "Product slows", "No effect", "Only temp", 0, "Mn²⁺ autocatalyst."),
      Q("Light Br₂ + alkane:", "Substitution slow dark", "Fast with UV", "No reaction ever", "Only addition", 1, "Radical chain."),
      Q("Concentration-time zero order:", "Straight line ln conc", "Linear decrease conc vs t", "Exponential", "Flat", 1, "Rate constant."),
      Q("Half-life zero order depends on:", "Initial conc", "Constant always", "Catalyst only", "Volume only", 0, "t½ = [A]₀/2k."),
      Q("Stirring flask solid + liquid:", "May increase rate dissolving", "Never helps", "Only gas", "Stops reaction", 0, "Surface refresh."),
      Q("Enzyme substrate saturation:", "Rate levels Vmax", "Rate infinite", "Rate zero", "Only low [S]", 0, "Michaelis-Menten shape."),
      Q("Explosion limit gas:", "Concentration window", "Always all ratios", "Only liquid", "Only catalyst", 0, "Fuel/air limits."),
      Q("Catalyst poison lead on Pt:", "Blocks active sites", "Speeds more", "Adds reactant", "Removes product", 0, "Deactivation."),
      Q("Orientation important:", "Bimolecular reactions", "Only atoms", "Never", "Only solids", 0, "Steric."),
      Q("Clock reaction I₂ starch:", "Sudden blue-black after S₂O₃²⁻ used up", "Immediate", "Never colour", "Only gas", 0, "Iodine clock."),
      Q("Quench with ice:", "Slow molecular motion", "Speed up", "Evaporate", "Only metal", 0, "Freeze rate."),
      Q("Pressure cooker food:", "Higher bp water faster cooking", "Lower bp", "No effect", "Only colour", 0, "Rate and T."),
      Q("Nanoparticle catalyst:", "Larger surface per mass", "Smaller surface", "No surface", "Only bulk", 0, "More active sites."),
      Q("Rate law from experiment:", "Stoichiometry coefficients always", "Must measure orders", "Only theory", "Always 1", 1, "Empirical orders."),
      Q("Arrhenius k = A e^{-Ea/RT} T↑:", "k decreases", "k increases", "k constant", "k zero", 1, "Exponential."),
    ],
    trueFalse: [TF("A catalyst increases the rate of both forward and reverse reactions.", true, "Ea lowered both ways."), TF("Higher temperature always increases rate for elementary steps.", true, "More molecules exceed Ea."), TF("Increasing surface area of a solid reactant has no effect on rate.", false, "More collisions at surface."), TF("All reactions are zero order.", false, "Orders vary."), TF("Catalyst appears in overall balanced equation.", false, "Regenerated."), TF("Collision frequency alone determines rate.", false, "Energy and orientation matter."), TF("Instantaneous rate can change during reaction.", true, "Concentration drops."), TF("Measuring rate requires only final yield.", false, "Need time data."), TF("Enzymes are specific to substrate shape.", true, "Lock and key."), TF("Increasing pressure in a solution reaction rarely affects rate like gases.", true, "Liquids nearly incompressible."), TF("A larger Ea means slower reaction at same T.", true, "Fewer successful collisions."), TF("Radioactive decay rate independent of temperature mostly.", true, "Nuclear not thermal activation.")],
  },
];
